### ISSUE TITLE
Update Logo/Theme

### ISSUE THREAD

**Issue by ryansolid** [ryansolid/solid#101]
I am not a visual artist. I used a logo generator. I think at some point in the near future Solid needs to get a real logo. Now I'm not necessarily inviting an open free for all as I don't want to waste anyone's time but I could definitely benefit from some help.

**Comment by atfzl** [comment]
<img width="1301" alt="Screenshot 2019-11-15 at 8 35 52 AM" src="https://user-images.githubusercontent.com/14862437/68913968-f7a2b580-0782-11ea-9278-bb86c5494348.png">

Just a font logo: https://fonts.google.com/specimen/Major+Mono+Display?selection.family=Major+Mono+Display

**Comment by ryansolid** [comment]
@atfzl It's arguably less cheesy than what I have right now. But I think I want to do something where I can get an icon out of it. This is probably going to take some custom work. It's another S library though so have to differentiate from like Svelte. Thanks for taking the time to try an idea.

**Comment by ryansolid** [comment]
Besides I'd have to give up terrible snake puns.

"The Reactive UI library that Scales"

Sorry that's really bad. It's just been in my head ever since I wrote the Cost of UI Component article.

**Comment by lukeshiru** [comment]
Something like this, maybe?

![](https://i.imgur.com/kknSYzB.png)

I did it keeping the idea of "solid" in mind, and trying to preserve the colors you choose for your current logo. I created every letter from scratch and the minimum size is 80x16 😄 

![](https://i.imgur.com/YttGaNj.png)

**Comment by ryansolid** [comment]
@lukeshiru Hey awesome work.. I played in a band for years that was called Solid and we had so many logos for posters, shirts, albums etc, and when I saw it elements reminded me of few of the ideas we'd played with at certain times.

I think this has helped me understand better what I'm looking for. It's really the Icon that I'm looking for as I think the rest of the logo should be easily readible. Some strong san serif font etc. I think the rest fills in easier once the Icons in place.

So what I really like here is that the S as an Icon is unique. Not that I don't appreciate how every letter looks carved out of a solid cube, it carries the weight well. But more importantly, that S you aren't going to confuse with Svelte. And that's what I think is important. To have something that stands out again the other Library Icons.

Given that clarity I want to see if that opens up some more ideas.

**Comment by blieque** [comment]
I plopped these together just now. I'm quite a fan of the suckless project logotypes. Could be made more distinctive for a good icon.

![solid][https://i.imgur.com/8WAXzEy.png]

**Comment by danbrianwhite** [comment]
IMHO the current logo is nice and gets the point across.
✔️ Deceptive
✔️ Simple

**Comment by s0kil** [comment]
As @danbrianwhite said, it gets the job done whilst looking good.

**Comment by ryansolid** [comment]
Thanks. I didn't put zero thought into. I just always feel like this is a weakness of mine. Although it feels that my day job pushes me more towards Product Management than development every day, so maybe my sense isn't completely off. Although that sense is telling me the current stuff is undeniably a bit cheesy.

Honestly I figured I'd be building the website by now(which is why I was looking at a facelift) but there has been a lot of really interesting dev stuff around Suspense and SSR keeping me busy, as I creep through building the Real World Demo. So I'm in no rush let's keep this open.

**Comment by ddibiase** [comment]
I have two of my team’s designers working on some ideas. Will post them once we have something worth showing :-)

**Comment by ddibiase** [comment]
I actually really like the simplicity of @atfzl's solution but I understand the need for a single icon/element.

Here are a couple concepts I put together to generate some further thought. I put the whole word Solid beside it to show that they can exist together or on their own. These are not ideas generated by my team, I'll post those shortly. These would all have to be redrawn and balanced be a *real* graphic designer (which I am not!) :-p

**Concept 1** - Isometric-like S that has some components that look like a snake. Looks good without the containing circle.
 
<img width="645" alt="Screen Shot 2020-01-25 at 2 59 59 PM" src="https://user-images.githubusercontent.com/1168397/73126697-d977e380-3f83-11ea-8565-a070b612e47a.png">

**Concept 2** - Attempted using the typography and the S again. The current logo follows this trend so I'm just re-imaging it within Ryan's original concept.

<img width="972" alt="Screen Shot 2020-01-25 at 3 01 59 PM" src="https://user-images.githubusercontent.com/1168397/73126707-e8f72c80-3f83-11ea-81fc-1167295503b4.png">

**Concept 3** - A departure from the previous two concepts. The S could be layered and have more slender qualities instead of the blocky concepts above.

<img width="743" alt="Screen Shot 2020-01-25 at 3 10 34 PM" src="https://user-images.githubusercontent.com/1168397/73126789-da5d4500-3f84-11ea-9216-87409983d25d.png">

**Comment by ryansolid** [comment]
Wow. That's so awesome. These are all really good. I like them all. I wasn't expecting play on the snake but I actually like that more than I expected. The flat logo design of the 3rd I think with the right colors could hold it's own when juxtaposed with Angular, Vue, React, or Svelte. The snake there really makes it stand out and not get confused with another S library (like Svelte or Storyboard). I'm already like what I'm seeing a lot. I'd be stoked to see what your designers come up with. I really appreciate it.

**Comment by ddibiase** [comment]
That's great to hear Ryan. Happy to support the great work you're doing here. Once they come up with something I like, will certainly post it.

Concept 3 is interesting and with proper illustration skills could look really great. I was personally more excited by the first two concepts though.

PS. I highly encourage other community members to have a shot. Maybe someone wants to take Concept 3 and iterate on it? Communal design FTW.

**Comment by ddibiase** [comment]
Thanks for the kind comments. Sorry for the delay since the last upload, we got busier with a delivery than expected. Here are some more concepts. They are pretty all over the place, just throwing ideas at the wall:

**Concept 4** - Really clean and very concise. I actually like this concept more than the others.
<img width="1057" alt="Screen Shot 2020-02-12 at 8 53 45 PM" src="https://user-images.githubusercontent.com/1168397/74394151-0c223880-4dda-11ea-9ee9-8c599650b07b.png">

**Concept 5** - Something a bit more basic but something about the 3D is interesting. Haven't seen that done too much.
<img width="1006" alt="Screen Shot 2020-02-12 at 8 54 00 PM" src="https://user-images.githubusercontent.com/1168397/74394152-0cbacf00-4dda-11ea-9ea7-90d701fa3246.png">

**Concept 6** - Experimentation with some shapes/geometry.
<img width="1069" alt="Screen Shot 2020-02-12 at 8 54 04 PM" src="https://user-images.githubusercontent.com/1168397/74394155-0d536580-4dda-11ea-846d-c8cb206cfba5.png">

**Concept 7** - Another great contender. Simple, elegant and still looks interesting.
<img width="977" alt="Screen Shot 2020-02-12 at 8 54 14 PM" src="https://user-images.githubusercontent.com/1168397/74394159-0debfc00-4dda-11ea-8e7e-67ed683efb50.png">

**Comment by ryansolid** [comment]
Wow you outdid yourself again. All of these are way better than anything I could do. I think these are much better logos than many businesses have.

I really like the font face and stance of concept 4. It's unique and stands out. Something about the 3d on the S keeps throwing me off a bit. Something about the positioning. Can't place it but otherwise I think it's the best of the bunch.  I also really like 7 and the flat design, and although it is more similar to other logos I've seen in the past, but that would be my only comment. Although if not single other submission came in I could easily work with that. And that might just be the case because these are all really impressive.

**Comment by ddibiase** [comment]
Glad to hear this new batch provided more viable options. I think concept 4 is more unique and while strange visually it has a memorable element to it. Definitely much different than other OSS projects. I’d encourage you to go with it but concept 7 works well too.

Of course I continue to encourage the community to take these ideas and iterate them! These are conceptual and if they give way to something stronger then...amazing :-)

If you plan to launch a new dedicated website for solid let me know. I’d be happy to donate some design and development time.

**Comment by aguilera51284** [comment]
i vote for concept 3

**Comment by yuens1002** [comment]
hey ryan, why the snake in the current solid logo?  just curious to see if you had some thoughts about solid you'd like share to collectively think about what should the logo say about the framework.

**Comment by bikeshedder** [comment]
@yuens1002 I had the exact same question.

I wonder if it is an allusion to [Solid Snake](https://en.wikipedia.org/wiki/Solid_Snake) from [Metal Gear](https://en.wikipedia.org/wiki/Metal_Gear).

**Comment by ddibiase** [comment]
@bikeshedder haha didn't think about that. That's a really funny reference if it's true.

**Comment by ryansolid** [comment]
@yuens1002 and @bikeshedder 

I'm going to attribute this to logo generator. I didn't have any particular attachment to the snake.

Truthfully I was just going through a bunch of options and wanted something that worked with the "S". There were a lot of 3D block sort of things that just looked to basic and uninteresting. I was definitely cognizant of Solid Snake of Metal Gear but I was just trying to to think of something I could make a tagline out of as a well. I particularly liked the phrase "deceptively simple" which worked with the snake and had some nice alliteration even though hard to say if it's flattering or not. So when I saw the snake, I pieced all of those things together as good enough to move forward with.

Since then I may have grown more fond of the snake but it is simply because although historically seen as symbol of evil, I think of it more playfully. Solid as a framework while on the surface is very familiar looking. But I'm definitely trying to pull people over to the dark side so to speak. It presents this comfortable API but under the hood it goes against conventional knowledge, eschewing the use of Virtual DOM, minimizing the mechanical role of Components, using JSX templating with a Reactive library.. and so on. If you look at articles/talks from any of the major libraries, React, Vue, Svelte, etc.. many of these things are thought as not possible or not good ideas. But Solid does it in a way that you don't even realize you're already past that point. You've already drank the Kool-Aid. For what I see as a disruptive change to how UI libraries work, it is deceptively subtle.

**Comment by yuens1002** [comment]
Well said Ryan, will share your thoughts with someone I know who may be
able to help us.

**Comment by s0kil** [comment]
It's funny how the logo is now the most commented issue regarding `solid-js`.

**Comment by ddibiase** [comment]
@s0kil still a young community. Ryan is busy factoring a first official release while the rest of else are helping him bring the brand to life. The brand should reflect the goals of the project but also be approachable. It has to look and feel as professional as other OSS projects (IMO). Here are some additional concepts:

**Concept 8A** - Playing with the combination of circle and S.

<img width="754" alt="Screen Shot 2020-03-15 at 11 49 02 AM" src="https://user-images.githubusercontent.com/1168397/76705210-b2e94580-66b4-11ea-8d20-432e97d31508.png">


**Concept 8B** - Similar to above although slight variation with colouring of the circle.

<img width="757" alt="Screen Shot 2020-03-15 at 11 49 11 AM" src="https://user-images.githubusercontent.com/1168397/76705201-9f3ddf00-66b4-11ea-93bf-4b3c39e25401.png">

**Concept 8C** - Once again a similar concept however with some inner gradient to help emphasize the S.

<img width="753" alt="Screen Shot 2020-03-15 at 11 49 16 AM" src="https://user-images.githubusercontent.com/1168397/76705235-e1672080-66b4-11ea-986f-a1d46f1de55a.png">

**Concept 9A** - Simple and slightly more corporate feel.

<img width="765" alt="Screen Shot 2020-03-15 at 12 04 47 PM" src="https://user-images.githubusercontent.com/1168397/76705277-3acf4f80-66b5-11ea-8d8b-7be22b588a57.png">

**Concept 9B** - Similar variation with a smaller s. Not too much of a fan of this but might trigger some ideas for others.

<img width="766" alt="Screen Shot 2020-03-15 at 12 04 54 PM" src="https://user-images.githubusercontent.com/1168397/76705276-34d96e80-66b5-11ea-9dfa-8051bb0fa211.png">

**Comment by s0kil** [comment]
@ddibiase Concept 8A looks really good.

**Comment by s0kil** [comment]
It would be interesting for a logo to represent "solid" as in firm and stable in shape; not liquid or fluid.

**Comment by ddibiase** [comment]
@s0kil I generally agree. I'm trying to move away from the snake-concept. While a Metal Gear fan not sure if it plays well with how this community should be portrayed. I'm personally still loving Concept 4. My designer and I put together a few more variations.

The 3D is very different but together they look like a solid form, kind of like gears fitting together. Of course it's super abstract but I love how they emphasise the "S".

**Concept 4A** - Originally concept 4

<img width="1037" alt="Screen Shot 2020-03-15 at 12 13 09 PM" src="https://user-images.githubusercontent.com/1168397/76705507-de6d2f80-66b6-11ea-817b-2b1ab538f147.png">

**Concept 4B** - Different angling or slightly better balance in case the above angle looks awkward for anyone.

<img width="923" alt="Screen Shot 2020-03-15 at 12 13 17 PM" src="https://user-images.githubusercontent.com/1168397/76705514-e88f2e00-66b6-11ea-8d8b-fea6f8faf50d.png">

**Concept 4C** - Different angle and thickness.

<img width="881" alt="Screen Shot 2020-03-15 at 12 13 05 PM" src="https://user-images.githubusercontent.com/1168397/76705524-fba1fe00-66b6-11ea-9abe-84ebd7b381af.png">

**Concept 4D** -  Stacked and aligned properly it forms an S and looks like a solid figure/body.

<img width="901" alt="Screen Shot 2020-03-15 at 12 13 29 PM" src="https://user-images.githubusercontent.com/1168397/76705541-2e4bf680-66b7-11ea-9ec8-50bb8d4ef806.png">

**Concept 4E** - Completely different angling.

<img width="957" alt="Screen Shot 2020-03-15 at 12 13 32 PM" src="https://user-images.githubusercontent.com/1168397/76705547-39068b80-66b7-11ea-8085-ae08956ad1ff.png">

Sorry to re-hash this concept. There's something that I personally love about it. If it doesn't work though, oh well :-p just wanted to give it one final try to see if it spikes any interest in the community.

**Comment by rytone** [comment]
I'm really loving the way 4A and 4E are looking, super unique and memorable. I think it's important to really stand out above all the generic flat logos given how unique of a library Solid is.

**Comment by ddibiase** [comment]
Thanks for the feedback @rytone. That was the goal. It would be really great if we got more feedback (positive or negative) regarding these directions. Please voice your opinion!

**Comment by ddibiase** [comment]
Here's a completely flat version of the logo for everyone to give feedback on.

![unnamed](https://user-images.githubusercontent.com/1168397/77233306-fc3a0900-6b7c-11ea-99f1-b21bbb49751f.png)

Although admittedly as I ask around and get feedback I have more people suggesting the following work very well for us. I'm consolidating/renaming them as official contenders.

We also haven't received much other feedback. Once again would love to see more coming in from the community. Please help by contributing constructive criticism. =)

**Concept I**

<img width="1037" alt="76705507-de6d2f80-66b6-11ea-817b-2b1ab538f147" src="https://user-images.githubusercontent.com/1168397/77233291-e7f60c00-6b7c-11ea-8dc7-2be9e8b8d188.png">

**Concept II**

<img width="957" alt="76705547-39068b80-66b7-11ea-8085-ae08956ad1ff" src="https://user-images.githubusercontent.com/1168397/77233297-ee848380-6b7c-11ea-95f0-6ba5223f4614.png">

**Comment by ryansolid** [comment]
This thread is nearing end of life. With the work I'm doing nearly done, the last task for 1.0 is the website, so I intend to use what I have available. To that end, if anyone is still holding out ideas, or has feedback on the proposed ones I could really use your help. Any feedback/comment could help a lot. I'm going to have to draw a line pretty quick here. If I can have everyone's contribution by Thursday, March 26th. Thanks again for helping through this process.

**Comment by amoutonbrady** [comment]
Hey, I've been asking my web developer colleague as well as some project manager and they all seemed to be attracted to the **Concept I** logo from the latest post. 

They don't know much about the library and they mainly picked what standed out the most. I for myself also really like this one. There's a bold aspect that kind of say "Hey I'm here to stay" if that makes any sense :p

**Comment by ryansolid** [comment]
Thank you guys for all your feedback. It was really helpful. Especially thanks to @ddibiase for creating the logo. We've settled on Concept 4a. I think it does have this bold characteristic that makes it standout. The website will be coming soon.
