### ISSUE TITLE
[TS] Nested state paths & custom Partial helper

### ISSUE THREAD

**Issue by r0skar** [ryansolid/solid#104]
Having some minor Typescript issues with nested state paths, I came across this type declaration:

https://github.com/ryansolid/solid/blob/cee416994ef62ad2fd7e6b7eb9b9a251eed86c34/src/state.ts#L11

Is there any reason not to use the built-in `Partial` helper? It seems to me that simply removing this custom definition makes a few of my TS errors go away.

The code in question:

```ts
interface State {
  isVisible: boolean
  item: {
    next?: Item
    prev?: Item
  }
}

const [ state, dispatch ] = createState<State>({
  isVisible: true,
  item: {
    next: undefined,
    prev: undefined
  }
})

// TS error: Type 'Item' is not assignable to type 'Partial<Item>'
dispatch(s => ({ isVisible: false, item: { ...s.item, next: 'next' } }))
```

**Comment by ryansolid** [comment]
I actually think the types are incorrect now that I look at it. Probably the reason for the confusion around nested typing. It's only the top-level object (whether first argument or on a nested path) that is a partial, so the recursive definition is wrong which is likely the whole reason the helper wasn't used. This should be easy to address. Thanks for bringing this to my attention.

**Comment by ryansolid** [comment]
I believe I have better type defs now in v0.14.10. Let me know if that addresses the issues you were seeing.

**Comment by r0skar** [comment]
My warnings are gone. Thanks for to quick response :+1:
