### ISSUE TITLE
Minimal TypeScript setup?

### ISSUE THREAD

**Issue by schtauffen** [ryansolid/solid#105]
I am trying to explore solid-js w/ SSR. I have set up a minimal example with the solid-preset and typescript to begin my hacking, but cannot seem to find what is required for it to function.

repo:
https://github.com/schtauffen/minimal-solid-ts

**Expected:** "Hello Zach" renders on page.
**Actual:** Receive error:  
> Unexpected token, expected ";" (3:41)

I've been comparing contrasting with how it is set up in the _app-ts_ template but haven't determined the issue yet.

**Comment by ryansolid** [comment]
Ok, I'm probably going to need to pull this down to have a look. One thing I see on the surface is that Solid's render function has a slightly different form than React. The first argument needs to be wrapped in a function:
```jsx
render(
  () => <HelloMessage name="Zach" />,
  document.getElementById('root')
)
```
I'm gathering that alone probably won't fix it. But it's a start. I will let you know when I fine more.

**Comment by ryansolid** [comment]
Ok got it to work. TypeScript seems to be particular about the `.tsx` extension whereas JavaScript not so much. Other than the change mentioned about all I did was change the extension to `.tsx` add that to the appropriate places in the webpack config and it built. Then I threw an index.html in so I could see it and it looks fine.

Changes:
```js
const config = {
  entry: './src/index.tsx',
  resolve: { extensions: ['.tsx', '.ts', '.js', '.json'] },
  module: { rules: [{ test: /\.(ts|tsx)$/ }] }
}
```

My guess is TypeScript gets its hands on it first, and it doesn't think to handle the TSX without the extension (even though it preserves it). There may be another way to solve this but it's a TypeScript meets Babel/Webpack issue.

**Comment by schtauffen** [comment]
Thanks @ryansolid! Debugging this was making me crazy.
