### ISSUE TITLE
solid-scripts start and HTTPS?

### ISSUE THREAD

**Issue by MikaelPorttila** [ryansolid/solid#110]
Hi, 

Is there an argument for enabling HTTPS while debugging using the solid-script start command or any other alternatives?

**Comment by ryansolid** [comment]
Yeah you should should be able to run
`HTTPS=true npm start`

solid-scripts is a port of Create React App so I believe this documentation should apply: https://create-react-app.dev/docs/using-https-in-development/

**Comment by MikaelPorttila** [comment]
Works perfectly 👍, thank you for the quick reply.
