### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by aguilera51284** [ryansolid/solid#114]
i find this router for solid
[solid-router](https://github.com/mduclehcm/solid-router)

would this apply to the related projects section?

**Comment by ryansolid** [comment]
It could @mduclehcm has been making some good contributions to DOM Expressions the core rendering underpinning of Solid. I haven't had a chance to review this in depth nor really decided how far I want to take linking repos on the official repo. So far they have just been ones that are part of the core technology or part of this repo. But things like routing are necessary pieces. I'm just not sure I want to stamp a "this is the solution" on anything just yet. CSS in JS is another thing that I'm thinking about along these lines. I'm probably going to publish a super small library that works with Solid for it but is it official?

What might make more sense is an awesome-solid repo, but I don't think we are there yet, and I am not focusing on that just yet but I do understand the desire for resources. I just don't want to get in the way of the community maintaining that. I'd link a repo like that off the main repo.

**Comment by aguilera51284** [comment]
ok ... but the same section says "related", it does not specify that it is the solution

**Comment by ryansolid** [comment]
You are absolutely right.

I want to do more to facilitate the community here and prevent things from drying up. I did reach out to find out the status of that project when it was unclear if it was being maintained. I think I need to endeavor to embrace these projects more. I will add a community section to the readme as I am made aware of more interesting projects. Honestly I need all the help I can get, and if contributing to the core is difficult community projects are a great way. 

I think we make this shift moving forward. And I will close this as done for now,
