### ISSUE TITLE
Build-error from fresh solid-scripts app-ts generated with typescript.

### ISSUE THREAD

**Issue by Seanmclem** [ryansolid/solid#117]
`npm init solid app-ts my-app` generates an app properly and `npm run start` starts a functioning app and dev-server, but the console shows an error:
`Attempted import error: '!!../node_modules/babel-loader/lib/index.js??ref--5-oneOf-2-1!./index.tsx' does not contain a default export (imported as 'Comp').`

Error shows without any code changes, or with some, after generating a new project, with Typescript

**Comment by ryansolid** [comment]
Thanks for reporting. Probably related to the new HMR module I added. I will address thus as soon as I can.

**Comment by ryansolid** [comment]
Should be fixed in scripts v0.0.28. I haven't done a full from scratch install yet but it worked fine updating my existing project with the structure. I'm going to do a full install and double check but you should be good.

**Comment by ryansolid** [comment]
Yeah confirmed with new install.

**Comment by Seanmclem** [comment]
That was quick, thanks!
