### ISSUE TITLE
relative URIs in production build?

### ISSUE THREAD

**Issue by joergplewe** [ryansolid/solid#120]
Hi!

I have some trouble serving the production build bc. the URI for `*.css` and `*.js` start with `/`.
Is it possible to use relative URI starting with `./` instead?

**Comment by ryansolid** [comment]
Ok. Hmm.. I think there is a way to set the root in production mode. I use it in the hacker news example. I think relative pathing can also get into trouble. In all honesty this is a straight port of Create React App so I follow exactly how they do stuff so I trust they've worked through these sort of details. Let me see if I can find it.

**Comment by ryansolid** [comment]
Yeah it's pretty hidden in their docs. They use the homepage field in package.json. https://create-react-app.dev/docs/deployment#building-for-relative-paths . I believe this can also be .env injected on variable PUBLIC_URL.

**Comment by joergplewe** [comment]
Great, thank you. `"homepage": "."` in `package.json` solves the issue.
