### ISSUE TITLE
React: equivalent solid apis

### ISSUE THREAD

**Issue by vmandi0app** [ryansolid/solid#126]
what are the equivalent apis of [**React.cloneElement**](https://reactjs.org/docs/react-api.html#cloneelement), [**React.Children**](https://reactjs.org/docs/react-api.html#reactchildren)   in solid?

**Comment by ryansolid** [comment]
Short answer is since we aren't dealing with a Virtual DOM those APIs meant for dealing with VDOM nodes don't make sense.

Of course the real question is what sort of scenarios you were picture using those methods with Solid? And we can see how we'd approach it reactively and identify any gaps.

**Comment by vmandi0app** [comment]
i am porting react code to solid. what is the best way to do this? part of my code is 
```jsx
render(){
  const {cls, className, clsActive, clsButton} = this.props;
  const {buttons} = this.state;

  return (
    <div className={`button-group ${cls} ${className}`}>
      {
        React.Children.map(this.props.children, (button, index) => {
          const correctIndex = index + 1;
          const isActive = buttons.includes(correctIndex);
          // here each children get new props
          return (
            React.cloneElement(button, {
              cls: button.props.cls + ' ' + clsButton + ' ' + (isActive ? clsActive === '' ? ' active ' : clsActive : ''),
              index: correctIndex,
              onClick: this.buttonClick.bind(this, correctIndex)
            })
          )
        })
      }
    </div>
  )
}
```

**Comment by ryansolid** [comment]
Right so wrapper Component applies click handler and sets active prop on children passed in rather than the parent. Hmm.. I've never actually used these APIs and always opted for a render prop which would work here. The problem is the children are rendered the second you access them which means unless you want to bind to the DOM nodes some more, which is doable although it bypasses the child's state management, you want to defer rendering until you have all reactive vars present. This probably means mapping the buttons to an array of functions that pass the active state in on the outside. But I will give this a shot tonight to see what it could look like.

**Comment by ryansolid** [comment]
I've made a Code Sandbox.  https://codesandbox.io/s/boring-bash-n72yd. I found 3 bugs in Solid through working on this example so I have a couple of things not perfect.

This example uses functions to inject the state from the wrapping component. This prop object uses  JS getters to wrap reactive expressions so they can be spread and maintain reactivity.

I'm still not convinced this is a good pattern. There might just be other ways to achieve this through other patterns. I'm not sure there are any additional helpers to generalize this either. All the tools are there I'm just not sure it's obvious.

**Comment by yuens1002** [comment]
solid i believe takes on the functional aspect of react and since the example is given in a class based react component, let's look at how we would rewrite the example as a functional component in react.

https://codesandbox.io/s/quizzical-clarke-o411h

if we then do a solid take, here's what you might have
https://codesandbox.io/s/quirky-mccarthy-s8w8l

**Comment by ryansolid** [comment]
This pattern is pretty useful in React and I think it generally is a fairly reusable there if the child components have an agreed upon interface. Classically things like routers have used this pattern to push route params down. The newer approach is to use Context + Hooks for routers. Kudos to the people who figured out this could be a thing and used it to slim-down some more challenging "slotting" scenarios with React.

It does suffer through from abstraction smell, in that it works by interacting directly with VDOM nodes, something we aren't supposed to be aware of. It's why they have special functions to hide the inner details there. That is why there is no real equivalent here as Solid has a similar abstraction but completely different implementation. If React ever moved away from a Virtual DOM (say some compiled solution) they could keep 90% of their abstraction but stuff like this would have to change.

I still see the problem though. It is insufficient to do the rendering of the children inside your own wrapper as that isn't reusable. We need to tell the `ButtonGroup` how to render each button. Personally if I were to do this example I would have the wrapper component (ButtonGroup) take following props:
* classes for the button group and buttons etc..
* The array of buttons it wants to draw, text, icon.. etc.. whatever information you need
* a render prop (or use children as a function) of the form `({ button, className, clickHandler }) => .....` where based on that info you could template the buttons however you want.. using conditionals to choose the right component etc.. In fact this function call could just be a Component definition. ie `const Button =  ({ button, className, clickHandler }) => .....` And then your wrapper could be used like `<ButtonGroup buttons={buttons} render={Button} />`

The shape of the buttons data is whatever you want to pass to yourself to later render the button so it can be pretty much anything. And this way the wrapper can pass its information through and you have a generic factory for generating the right child components based on the data being passed in. I'm pretty sure that's the pattern I'm going to recommend here unless it is missing a particular case.

**Comment by yuens1002** [comment]
Agree. I did however wanted to mimic the intent of the example. Passing a
shell to fill it with details from on the wrapper component which then hold
the states of rendered components.

**Comment by ryansolid** [comment]
Thread seems inactive. Closing.
