### ISSUE TITLE
0.17 occasionally breaks list rendering

### ISSUE THREAD

**Issue by niklasbuschmann** [ryansolid/solid#131]
The script then fails with a `Type error: n is undefined` in this [line](https://github.com/ryansolid/solid/blob/master/packages/solid/src/signal.ts#L351).

The issue seems to be that sometimes `source.observers` is a sparse array with a `.length` greater than the actual length, allowing `.pop()` to return `undefined`.

Unfortunately I am not able to provide a simple example where this occurs, but there are [apps](https://github.com/niklasbuschmann/zenreader) that break when updating to version 0.17.

**Comment by ryansolid** [comment]
Thanks for reporting. I tried to test in every scenario I had but this release saw a rewrite of the reactive core. I will investigate. The observers array should always be push and pop but maybe there is a bug in how items are moved in unsubscribe. Obviously any more details are helpful but I will investigate none the less.

**Comment by niklasbuschmann** [comment]
My observation was that including the following check for sparseness after line [347](https://github.com/ryansolid/solid/blob/master/packages/solid/src/signal.ts#L347), will only trigger immediately before and when failing:

```js
if (source.observers.length !== source.observers.filter(Boolean).length) {
  console.log(Array.from(source.observers));
}
```

<img width="501" alt="Screenshot 2020-03-25 at 16 26 43" src="https://user-images.githubusercontent.com/4943215/77553731-7805bf80-6eb5-11ea-93a4-b304fb3fec46.png">

**Comment by ryansolid** [comment]
Thanks I downloaded your app and found an easy to reproduce scenario with the subscribe button. Your last hint is helpful. I see it happening now just trying to figure out how the indexes are getting out of sync.

**Comment by ryansolid** [comment]
Ok update. I know what the problem is just deciding on the right fix. Logic was too simple to handle duplicate nodes in the list. In practice checking uniqueness all the time is more expensive than just adding deps that will never run anyway, but obviously if the disposal logic can't handle it we have a problem.

**Comment by ryansolid** [comment]
Seems almost too simple of a fix but I realized it is what the old version was doing. Checking node equality was just messing things up.
