### ISSUE TITLE
Default args in components?

### ISSUE THREAD

**Issue by delaneyj** [ryansolid/solid#136]
Creating a font awesome component in Solid.  Would like to have defaults to you don't have to set for example the base every time and show a blatant default name prop to make sure its temporary.

```
import { IconName, IconPrefix } from '@fortawesome/fontawesome-common-types'
import { classes } from 'typestyle'
import { setDefaults } from 'solid-js'

export interface ButtonProps {
  name: IconName
  base: IconPrefix
}

export default function FontAwesomeIcon(props: ButtonProps) {
  setDefaults(props, { name: `biohazard`, base: `fas` })
  const iconClasses = classes(props.base, `fa-${props.name}`)
  return <i class={iconClasses} />
}
```

Trying to use it without all props ala `<FontAwesomeIcon />` gives 
```
Type '{}' is not assignable to type 'IntrinsicAttributes & ButtonProps'.
  Type '{}' is missing the following properties from type 'ButtonProps': name, base
```
Found the `setDefaults` function but doesn't appear to work like I'd expect.  What am I doing wrong?

**Comment by ryansolid** [comment]
I think that if your props are optional then you need to indicate with the props definition. Admittedly I haven't done enough TypeScript development with other libraries but it makes sense to me to work this way since the Component definition should be able to define what is required.

What happens if you change it to (notice the question marks)?
```ts
interface ButtonProps {
  name?: IconName
  base?: IconPrefix
}
```

**Comment by delaneyj** [comment]
100% correct, getting used to JSX... thanks.

**Comment by ryansolid** [comment]
Yeah.. JSX + TypeScript might be about the worst part of TypeScript. It was my introduction unfortunately, I came across(existing) and wrote about 5 issues just in the first week or so of learning TypeScript. Not really the best introduction.
