### ISSUE TITLE
Signal usage

### ISSUE THREAD

**Issue by delaneyj** [ryansolid/solid#138]
I'm missing something in my understanding of signals.  Testing making a toggle component.
```tsx
import { setDefaults } from 'solid-js'

import { ComponentProps } from '../types'
import { Show } from 'solid-js/dom'
import { style } from 'typestyle'

export interface ToggleProps {
  toggled?: boolean
  label?: string
  onClick?: (toggled: boolean) => void
}

export default function Toggle(props: ToggleProps) {
  setDefaults(props, { toggled: false, onClick: () => {} })
  const { toggled, label, onClick } = props

  const wrapper = style({
    display: 'flex',
    cursor: 'pointer',
  })

  return (
    <div onClick={() => onClick!(!toggled)} class={wrapper}>
      <Show when={!!label}>
        <div>{label}</div>
      </Show>
      <div>{toggled ? 'X' : '[]'}</div>
    </div>
  )
}
```

if I use the component ala  `<Toggle label="Foo" toggled={true} />` it is rendered properly.  Adding signals to control the component do not appear to effect it.

```
const [isToggled, setToggled] = createSignal(false)
  const click = (b: boolean) => {
    console.log(`Toggle changed to ${b}`)
    setToggled(b)
  }
 return (
    <div>
      <Toggle label="Foo" toggled={isToggled()} onClick={click} />
    </div>
  )
```
The console log does get hit but the component does not re-render.  I'm sure its a misunderstanding of how signals interact with jsx templates.  Thanks!

**Comment by ryansolid** [comment]
I doubt you are going to like the answer to this, but it's something that is pretty common in the MobX world and pretty much comes with the territory here. The reason this isn't working is because you are destructuring the props object. It is the property access that is reactive, so if you destructure there nothing is listening to the change. I do a pretty poor job of explaining it here: https://github.com/ryansolid/solid/blob/master/documentation/components.md#components

There are 2 ways to solve this:
1. Pass the signal directly and use it as a function in your child component.
```jsx
// from parent, with no parens passing the function down:
<Toggle label="Foo" toggled={isToggled} onClick={click} />
// in the child keep the destructure and call the function:
<div onClick={() => onClick!(!toggled())} class={wrapper}>
  <Show when={!!label}>
     <div>{label}</div>
  </Show>
  <div>{toggled() ? 'X' : '[]'}</div>
</div>
```
This is what you have to do in most other libraries like Solid. However, it has serious issues. What if the label could be dynamic? You would need to check if it receives a function or a value when you try to bind it. What if there is a sideEffect using it.. It's not just binding code that would need to make a decision. This is completely unacceptable from my perspective. You can do this if you want but the prefered way is:
2. Don't destructure outside reactive context unless you intend for the value to never change. In fact, there are many places I do this on purpose to tell the compiler that the value could never change. Rewrite your code to:
```jsx
// from parent, with no parens passing the function down:
<Toggle label="Foo" toggled={isToggled} onClick={click} />
// in the child keep the destructure and call the function:
<div onClick={() => onClick!(!props.toggled)} class={wrapper}>
  <Show when={!!label}>
     <div>{label}</div>
  </Show>
  <div>{props.toggled ? 'X' : '[]'}</div>
</div>
```

Thanks for writing these questions. These are exactly the kind things that I make sure are abundantly clear in the guides I will be writing for the website.

**Comment by delaneyj** [comment]
Happy to help.  I did read that doc but thought the destructing limits were only in the incoming parameter level.  Did did it working with your comments.  If its key to being faster I'm on board, but being super explicit about no destructing anywhere would be good in the docs.  Have you looked at [toRefs()](https://vue-composition-api-rfc.netlify.com/api.html#torefs) in Vue3?  Maybe at that point its better to just rely on the state interface in solid.

**Comment by delaneyj** [comment]
I made a `vuetify.ts` to help port from Vue3 to Solid signals ala 
```tsx
import { createSignal, createMemo, createEffect } from "solid-js"

export interface ComponentProps {
    class?: string
}

export class SignalWrapper<T> {
    getter: () => T
    setter: (t: T) => void

    constructor(initial: T) {
        const [g, s] = createSignal(initial)
        this.getter = g
        this.setter = s
    }

    get value(): T {
        return this.getter()
    }

    set value(value: T) {
        this.setter(value)
    }
}

export function ref<T>(initial: T) {
    return new SignalWrapper(initial)
}


export class Computed<T> {
    getter: () => T

    constructor(fn: (v?: T) => T) {
        this.getter = createMemo(fn)
    }

    get value(): T {
        return this.getter()
    }
}

export function computed<T>(fn: (v?: T) => T) {
    return new Computed(fn)
}

export function watch<T>(fn: (v?: T) => T, value?: T) {
    return createEffect(fn, value)
}
```
and changing over Toggle to use it mostly works
``` tsx
import { IconName } from '@fortawesome/fontawesome-common-types'
import { Show } from 'solid-js/dom'
import { style } from 'typestyle'

import { computed, SignalWrapper, watch } from '../vueify'
import FontAwesomeIcon from './FontAwesomeIcon'

export interface ToggleProps {
  toggleSignal: SignalWrapper<boolean>
  label?: string
}

export default function Toggle(props: ToggleProps) {
  const { toggleSignal } = props
  const wrapper = style({
    display: 'flex',
    cursor: 'pointer',
    userSelect: 'none',
  })
  const icon = computed<IconName>(() => {
    const i = toggleSignal.value ? 'check-square' : 'square'
    console.log(`In computed ${toggleSignal.value} ${i}`)
    return i
  })

  watch(() => {
    console.log(`In watch ${icon.value}`)
  })

  return (
    <div onClick={() => (toggleSignal.value = !toggleSignal.value)} class={wrapper}>
      <Show when={!!props.label}>
        <div>{props.label}</div>
      </Show>
      <FontAwesomeIcon name={icon.value} />
    </div>
  )
}
```
However clicking on the wrapping `div` does dump to the console
```
Toggle changed to true
Toggle.tsx:22 In computed true check-square
Toggle.tsx:27 In watch check-square
```
But does not render the change in the DOM.  As the `.value` is just a  wrapper around the signal's getter is that indirection causing a problem?

**Comment by ryansolid** [comment]
@delaneyj 
I think a lot of people would appreciate something like that Vueitify util. So super cool. I think I need the rest of the example. I think the issue might not be in the code I'm' seeing.
-----------------------------
And...
The problem with `toRefs` is I feel it solves an unnecessary problem. Is `isToggled.value` better than `props.isToggled`? If anything props is not a special name. It could be `p.isToggled`. If anything you just added another wrapper layer, did an extra destructure, and still are writing more code.

I mean it could just destructure back to signals, but the worst thing is that it doesn't help us in the primary destructuring case, the function declaration. You don't get to:
```ts
export default function Toggle({ toggled, label, onClick }: ToggleProps) { }
```
Now this might be my React bias showing. But that is the way you destructure in React pretty much always. Anything else rarely comes into play. And it makes a lot of sense for library dealing in function components all the time. It's very hard to have the helper not help the primary case. People will do this by accident and I can't prevent this.

My feeling is the biggest problem is people not knowing about this, not that once they know they need or particularly want it. I've thought of really cool API's to accomplish if it ever made sense to go this way. You could even have it automatic as a destructure mechanism using a proxy.

**Comment by ryansolid** [comment]
We worked through the issue here. A property access outside reactive context. I'm going to close but @delaneyj feel free to reopen if there is more here. And keep these ideas coming. I've worked with people porting React but Vue is new for me so I'd be interested just how possible/easy it is.
