### ISSUE TITLE
Updated state does not update child component

### ISSUE THREAD

**Issue by cannahum** [ryansolid/solid#160]
I love the work that's being done here. There is a chance I don't understand the updating mechanism of Solid JS, so I'm hoping to get an answer here.

I have a small Counter component which has some states:

- Counter is easy, increment, decrement. Nothing interesting here.

- There is a child component (my component) that I call FormInput. User inputs a value, and based on parseInt, I change how much I increment and decrement.

- If I can't parseInt, then I set an error state.

```TypeScript
function Counter() {
  const [currentCount, setCount] = createSignal(0);
  const [delta, setDelta] = createSignal(1);
  const [deltaError, setDeltaError] = createState({ error: undefined });

  const increment = () => {
    setCount(currentCount() + delta());
  };

  const decrement = () => {
    setCount(currentCount() - delta());
  };

  const onDeltaChange = (v: string) => {
    try {
      const x = parseInt(v);
      if (isNaN(x)) {
        throw Error("fuck");
      }
      if (x !== delta()) {
        setDelta(x);
      }
    } catch (e) {
      debugger;
      setDeltaError({error: e.message});
      console.log(deltaError);
    }
  };

  return (
    <div>
      <h2>Counter</h2>
      <p>Current Count: {currentCount()}</p>
      <FormInput
        label="Count"
        name="count"
        onBlur={e => onDeltaChange(e.target.value)}
        errorMessage={JSON.stringify(deltaError)}
      />

      <button onClick={increment}>+</button>
      <button onClick={decrement}>-</button>
    </div>
  )
}
```

If the user types into the <FormInput /> something like "sdfsdf", then I should be seeing the deltaError. Even though when I debug, I do see that I set the error state correctly, and the hook works. BUT the <FormInput /> component won't update.

**Comment by ryansolid** [comment]
The code you shared looks fine. Solid lazily evals all `props` which suggests to me the problem more than likely in the code I can't see: `FormInput`.  If I had to guess it's possible you destructured the props outside of a reactive scope. This doesn't work in reactive libraries that rely on property access to track reactivity.

Can you share `FormInput`?

**Comment by cannahum** [comment]
Yes indeed, I was destructuring early. 

```typescript
unction FormInput({ label, errorMessage, ...props }: JSX.InputHTMLAttributes<HTMLInputElement> & FormInputProps) {
  return (
    <div class="form-input-wrapper">
      <label class="form-input-label">{label}</label>
      <input class="form-input" {...props} />
      {errorMessage ? (
        <p class="form-input-error error-message">{errorMessage}</p>
      ) : (
        <p class="form-input-error error-message">No errors</p>
      )}
    </div>
  );
}
```

When I stopped destructuring, it worked. Thank you!

How can I know what block is considered reactive?

**Comment by ryansolid** [comment]
I try my best to avoid unnecessary updates. In so nothing should be reactive unless you wrap it yourself (`createEffect` or `createMemo`) or access it from a binding. Keep in mind you don't need to wrap everything in a `createMemo`. If you don't need to cache the value, simply wrapping in a function `() => ...` is sufficient to wrap some derived state to be used later in a binding. Components are wrapped in `sample` so they don't track by default. 

Essentially the mental model is the exact opposite of React. The Component executes once and the reactive hooks/bindings execute as needed. This means closures are never stale and it's the state inside that is always most up to date. With React on the other hand the Component executes every render cycle and the Hooks whitelist whether they re-run. This leads to stale closures and need for things like Hook rules.
