### ISSUE TITLE
Path-less state

### ISSUE THREAD

**Issue by kenfoo** [ryansolid/solid#161]
Hi

Are there any plans to introduce a useState function that is closer to React's useState, where it's easy to make use of multiple calls to useState to create multiple state variables (instead of creating one large state object and updating the fields of the state object using setter(path, value) ?
i.e.
```
const [counter, setCounter = useState(0);
const [clicks, setClicks] = useState(0);
...
```

One benefit that I could think of would be that the paths wouldn't be visible in final bundled code and could actually be mangled/minified by minifiers. The other being it's slightly simpler to code.

As I understand, it is possible for us to use any type of key as the path to the setter, even numbers. So using the counter example, this works.

```
const COUNT = 0;
const App: Component = () => {
  const [state, setState] = createState({ [COUNT]: 0 }),
    timer = setInterval(() => setState(COUNT, c => c + 1), 1000);
  onCleanup(() => clearInterval(timer));

  return <div>Count is: {state[0]}</div>;
};

render(() => <App />, document.getElementById("app"));

```

Perhaps it would be possible to create a wrapper around createState such that it would increment an internal count as the path, and return a setter which is aware of this count value to be used as the path in the call to setState?

**Comment by ryansolid** [comment]
I think `createSignal` is what you are looking for. It's the single reactive atom and the state proxy is actually made of these. There are differences from `useState`. We need to track reads so the value has be lazily evaluated. Hence it is a function call. I suggest looking at the reactivity section of the docs https://github.com/ryansolid/solid/blob/master/documentation/reactivity.md#reactivity

**Comment by kenfoo** [comment]
Ah, yes. How could I have missed that. Thanks!
