### ISSUE TITLE
Context not compiling in Typescript

### ISSUE THREAD

**Issue by delaneyj** [ryansolid/solid#162]
Creating singletons signals but to avoid `index.js:354 computations created outside a `createRoot` or `render` will never be disposed` warning wanted to move to a context provider however using [typed version of example](https://github.com/ryansolid/solid/blob/master/documentation/context.md) won't build.

```tsx
import { createState, createContext } from 'solid-js';

export const CounterContext = createContext([{ count: 0 }, {}]);

export interface CounterProviderProps {
    count?: number
}
export function CounterProvider(props: CounterProviderProps) {
    const [state, setState] = createState({ count: props.count || 0 }),
        store = [
            state,
            {
                increment() {
                    setState("count", c => c + 1);
                },
                decrement() {
                    setState("count", c => c - 1);
                }
            }
        ];

    return (
        <CounterContext.Provider value= { store } >
        { props.children }
        < /CounterContext.Provider>
  )
}

```

Getting these errors
![image](https://user-images.githubusercontent.com/438252/83281766-6ed2f080-a18d-11ea-955a-bf5c34eb7964.png)
![image](https://user-images.githubusercontent.com/438252/83281843-8c07bf00-a18d-11ea-9088-fea6a163d264.png)

**Comment by ryansolid** [comment]
Wierd it's like it doesn't recognize it as JSX. Are you using the a `.tsx` extension? Or set the tsconfig to allow JSX in non-TSX files. I can dig a bit more into this later but that's what I'm reading from the errors. It's treating JSX <> as some sort of TypeScript operator either for generics or namespace or something.

**Comment by delaneyj** [comment]
It is in a `.tsx` file.  I had made a shim to avoid a host of other errors

```
declare namespace JSX {
    interface IntrinsicElements {
        [elemName: string]: any;
    }
}
```

**Comment by ryansolid** [comment]
It sounds like something very unusual is going on and not sure how to pinpoint it. I made a simple webpack build with TS if that helps: https://github.com/ryansolid/solid-ts-webpack

**Comment by ryansolid** [comment]
@delaneyj What should we do with this issue? Did you make some progress with getting a working setup?

**Comment by delaneyj** [comment]
yeah we are good now after the discussion on gitter with the addition of `ForIn `
