### ISSUE TITLE
Solid Styled Jsx not working with solid-scripts?

### ISSUE THREAD

**Issue by danielpza** [ryansolid/solid#170]
I made a new repo with `npm init solid app-ts my-app` installed `solid-styled-jsx` and created a `.babelrc` file with:

```json
{
  "presets": ["babel-preset-solid"],
  "plugins": ["solid-styled-jsx/babel"]
}
```

I made a component like so:

```tsx
function NumberButton({ value, big }) {
  return (
    <>
      <button>{value}</button>
      <style jsx>{`
        button {
          width: ${big ? 2 : 1}rem;
        }
      `}</style>
    </>
  );
}
```

Rendering the component doesn't transpile the style tag, it just renders it to the dom. as is.

Did I do something wrong? I looked up to the example https://codesandbox.io/s/solid-styled-jsx-xgx6b in the readme and only difference I can tell is they are using parcel instead of solid-scripts in the demo.

**Comment by ryansolid** [comment]
Solid's scripts is built off Create React App which gives very little control over the webpack build. It's a great starter but it doesn't give very much flexibility. CRA has this issue too. 

It looks like people have come up with creative ways to get around this in CRA (like hacking their own scripts), but I haven't done any work to see if the same would work here. I went this way so I could deliver a familiar dev experience quickly, but it's a very complicated build process. #144 sort of talks about alternative approaches.

I think at this point I have to say create-solid doesn't support solid-styled-jsx. I'm going to convert that CodeSandbox example to TypeScript to explore if I'm missing other TS stuff. I think Parcel 2 might be the easiest way to get started with it. It also might be worth looking at one of the starter templates others have made (some in #144) and go from there for the ability to add solid-styled-jsx.

**Comment by ryansolid** [comment]
Ok so I fixed and released the missing types bug in 0.18.5. I took the simple ts webpack template I have and adding styled-jsx to it and it seems to work good. I pushed it up under styled-jsx branch here: https://github.com/ryansolid/solid-ts-webpack/tree/styled-jsx

Give this a try and see if it will work for you.

**Comment by danielpza** [comment]
Thank you for putting up the template, I tried it and works fine, I'm really loving solid.

I'll leave the issue open so you can decide if you want to close it if that's the definitive answer for the question, or want to leave it up to track suggestions etc.

**Comment by ryansolid** [comment]
I'm going to close it as I'm more likely to completely replace how I do Solid Scripts before I address this. By that point given the solution this issue is sort of a non-issue. It will support custom Babel configs or it won't.
