### ISSUE TITLE
How to destroy a component

### ISSUE THREAD

**Issue by milovanderlinden** [ryansolid/solid#174]
First of all thank you for solidjs, I really enjoy playing with it!

I have a component in tsx that is a notification object. It has a close button and I would like it to destroy itself when a user clicks the close button. Can this be done? And if so how? I have been digging through code, issues and documentation but I cannot find any instructions. Please be aware that english is not my native language and that I may have been looking in the wrong places because of that.

**Comment by milovanderlinden** [comment]
```typescript
import './notification.scss'

interface Properties {
    type: 'success' | 'info' | 'warning' | 'error' //'TER INFORMATIE' | 'LET OP' | 'GELUKT' | 'STORING';
    title: string;
    description: string;
    id?: string;
}

/**
 * @class Notification
 * Listens for click events on the close button for notification to close the notification using javascript
 */
export const Notification = (properties: Properties) => {
    let typeTitle: string
    switch (properties.type) {
        case 'success': {
            typeTitle = 'Gelukt'
            break;
        }
        case 'info': {
            typeTitle = 'Ter informatie'
            break;
        }
        case 'warning': {
            typeTitle = 'Let op'
            break;
        }
        case 'error': {
            typeTitle = 'Storing'
            break;
        }
    }
    /**
     * Closes the notification
     */
    const close = () => {
        console.log("click");
    }

    return (
        <div class={`notification notification--${properties.type}`} id={properties.id}>
            <div class="notification__content">
                <div class="notification__type">{typeTitle}</div>
                    <h2 class="notification__title">{properties.title}</h2>
                    <span>{properties.description}</span>
            </div>
            <button class="notification__close-button" onclick={close}>
                <i class="icon icon-cross"></i>
                Sluit
            </button>
        </div>
    );
};
```

**Comment by ryansolid** [comment]
You have a couple options here. The thing to keep in mind is you are using these in a declarative view so a Component can't destroy itself. You can either keep the component mounted and toggle the children or the parent can remove it from its view.

The first has the advantage of being able to reuse the notification, but if you are having multiple at the same time potentially it isn't really an option. The latter approach is probably a bit simpler since it doesn't involve as much state synchronization. What you would do is expose an `onClose` prop.

So in your component you could do:
```tsx
import './notification.scss'

interface Properties {
    type: 'success' | 'info' | 'warning' | 'error' //'TER INFORMATIE' | 'LET OP' | 'GELUKT' | 'STORING';
    title: string;
    description: string;
    id?: string;
    onClose: () => void;
}

export const Notification = (properties: Properties) => {
    let typeTitle: string
    switch (properties.type) {
        case 'success': {
            typeTitle = 'Gelukt'
            break;
        }
        case 'info': {
            typeTitle = 'Ter informatie'
            break;
        }
        case 'warning': {
            typeTitle = 'Let op'
            break;
        }
        case 'error': {
            typeTitle = 'Storing'
            break;
        }
    }
    /**
     * Closes the notification
     */
    const close = () => {
        if (properties.onClose) properties.onClose()
    }

    return (
        <div class={`notification notification--${properties.type}`} id={properties.id}>
            <div class="notification__content">
                <div class="notification__type">{typeTitle}</div>
                    <h2 class="notification__title">{properties.title}</h2>
                    <span>{properties.description}</span>
            </div>
            <button class="notification__close-button" onclick={close}>
                <i class="icon icon-cross"></i>
                Sluit
            </button>
        </div>
    );
};
```

And then the caller could do something like:
```tsx
function handleDismiss() {
    setState({ notification: null })
}

return <Show when={state.notification}>
  <Notification {...state.notification} onClose={handleDismiss} />
</Show>
```

But it really comes down to how you are managing the showing of the notification. Is it a list of notications then just remove it from the list etc.. There are a lot of details in the implementation but more or less follow this pattern.

Feel free to shoot me any more questions if anything I said doesn't make any sense, or doesn't align with what you are trying to accomplish.

**Comment by milovanderlinden** [comment]
Thank you so much Ryan! I am going to work with your suggestion. It means that I need a component to wrap the notification in, because now I was handling it in a regular html <div>. Once I got something usefull, I will post it for others to use as example (if they want to).

**Comment by ryansolid** [comment]
I assumed it was already in something. If it is top level you can always just clear the mount element (second argument of the render function). Still involves passing the onClose in probably. But you can have the handler do the cleanup.

**Comment by milovanderlinden** [comment]
I managed to slightly alter your suggestion, making the notification component do the closing itself. It seems to works and it makes it unnecessary for the parent to be aware of the click event which in my opinion is better and makes the component stand on itself more.

```typescript
import './notification.scss'
import { createState, Show } from 'solid-js';

interface Properties {
    type: 'success' | 'info' | 'warning' | 'error' //'TER INFORMATIE' | 'LET OP' | 'GELUKT' | 'STORING';
    title: string;
    description: string;
    id?: string;
}

/**
 * @class Notification
 * Listens for click events on the close button for notification to close the notification using javascript
 */
export const Notification = (properties: Properties) => {
    const [state, setState] = createState({ notification: true });

    const handleDismiss = () => {
        setState({ notification: false })
    }
    let typeTitle: string
    switch (properties.type) {
        case 'success': {
            typeTitle = 'Gelukt'
            break;
        }
        case 'info': {
            typeTitle = 'Ter informatie'
            break;
        }
        case 'warning': {
            typeTitle = 'Let op'
            break;
        }
        case 'error': {
            typeTitle = 'Storing'
            break;
        }
    }
    /**
     * Closes the notification
     */
    const close = () => {
        handleDismiss()
    }

    return (
        <Show when={state.notification}>
            <div class={`notification notification--${properties.type}`} id={properties.id}>
                <div class="notification__content">
                    <div class="notification__type">{typeTitle}</div>
                    <h2 class="notification__title">{properties.title}</h2>
                    <span>{properties.description}</span>
                </div>
                <button class="notification__close-button" onclick={close}>
                    <i class="icon icon-cross"></i>
                Sluit
            </button>
            </div>
        </Show>
    );
};
```
And then the component is implemented in App.tsx like this:

```typescript
<Notification 
    type="warning" 
    title="Your title"
    description="Your description" />
```

**Comment by milovanderlinden** [comment]
By the way; my work in progress is here: 
https://github.com/codefornl/nl-design-system-solid
I am trying to make a reference implementation of a dutch design system in solidjs. As a hobby project.

**Comment by ryansolid** [comment]
Awesome. Yeah that was the other suggestion (what I meant by the component mounted and toggle the children). It gets a little more complicated when you want to control it from the parent as well since if you propagate the open stage upwards you need to also synchronize it downwards. But if this the top-level component and basically managing all the state this is by far the easiest way.

**Comment by milovanderlinden** [comment]
Thank you for the great help. I feel this one can be closed.
