### ISSUE TITLE
jsx.d.ts is missing "onclick" definition for ButtonHTMLAttributes<T>

### ISSUE THREAD

**Issue by milovanderlinden** [ryansolid/solid#176]
On an object like 
```typescript
<button class={`btn${properties.primary ? " btn--primary" : ""}`}
            disabled={properties.disabled}
            onclick={click}>
                {properties.title}
        </button>
```

This results in typescript giving a error hint

```typescript
Type '{ children: string; class: string; disabled: boolean | undefined; onclick: () => void; }' 
is not assignable to type 'ButtonHTMLAttributes<HTMLButtonElement>'.
Property 'onclick' does not exist on type 
'ButtonHTMLAttributes<HTMLButtonElement>'.ts(2322)
```

**Comment by ryansolid** [comment]
Hmm.. I streamlined all the TS defs a while back to be only CamelCased mirroring React. No real reason other than it was cleaner to have one way. Technically Solid supports both. I suppose they could be added back. Probably better. I was using TS as a more best practice kind of thing only documenting what I considered preferred path. Is it noisy to have both?

**Comment by milovanderlinden** [comment]
No no, it is fine! I notice that when I change it to camelcase, the error is gone.
