### ISSUE TITLE
CreateMemo documentation possibly out of date

### ISSUE THREAD

**Issue by boogerlad** [ryansolid/solid#178]
["Memos only notify dependents when returned value changes"](https://github.com/ryansolid/solid/blob/master/documentation/api.md#creatememoprev--code-initialvalue-comparatorfn-getvaluefn) However, https://codesandbox.io/s/async-resource-vznh2?file=/index.js logs to console every time the button is clicked despite the value not changing

https://codesandbox.io/s/async-resource-pp4mq?file=/index.js does not exhibit this behavior (has custom comparator). 

I think the issue is https://github.com/ryansolid/solid/blob/33436589f3abeecef2de892bc4856ce384c2039a/packages/solid/src/reactive/signal.ts#L113 where `areEqual` just doesn't have a default value. Of course, the documentation may have just grown stale.

**Comment by ryansolid** [comment]
Yep. It worked the way as documented for a very brief time period. I must have changed it and missed updating it back. I decided it was better to make it consistent with Signals in favor of updating to handle more scenarios.
