### ISSUE TITLE
Overmind - Cerebral with Solid

### ISSUE THREAD

**Issue by aguilera51284** [ryansolid/solid#179]
Hi, for a long time, I follow the work of  [Christian Alfoni](https://github.com/christianalfoni) with [cerebral ](https://cerebraljs.com/) and [overmind](https://overmindjs.org/), will be worth integrate are any of these state container integrating with solid-js?

**Comment by ryansolid** [comment]
I think they provide a great toolset especially devtools so I can see some value here. Someone asked me how to integrate it before so I made this codesandbox: https://codesandbox.io/s/solid-overmind-5m8cs?file=/index.js

I think it covers the basic cases but I'm not super familiar. This is the result of me playing with it a few hours.

**Comment by ryansolid** [comment]
I think the question is adequately answered. Closing. Reopen if I'm missing anything.
