### ISSUE TITLE
Context provider s rendering after its children

### ISSUE THREAD

**Issue by sushruth** [ryansolid/solid#182]
I have a pretty basic Context usage like below and I somehow see App component is rendered before Context component. Is this expected?

project created using using `yarn create solid app-ts example` - 

```tsx
// ---------- Context.tsx ----------------
import { Component, createContext, useContext } from "solid-js";

const ExampleContext = createContext(0);

export const ContextProvider: Component = ({ children }) => {
  console.log("Provider");
  return (
    <ExampleContext.Provider value={2}>{children}</ExampleContext.Provider>
  );
};

export function useExampleContext() {
  return useContext(ExampleContext);
}
```

```tsx
// ----------------- App.tsx ---------------------------
import "./App.css";
import { useExampleContext } from "./Context";

function App() {
  const d = useExampleContext();
  console.log('App - ', d)
  return <div class="App">App</div>;
}

export default App;
```

```tsx
// ------------------ Index.tsx --------------------------

import "solid-js";
import { render } from "solid-js/dom";
import App from "./App";
import { ContextProvider } from "./Context";
import "./index.css";
import * as serviceWorker from "./serviceWorker";

render(
  () => (
    <ContextProvider>
      <App />
    </ContextProvider>
  ),
  document.getElementById("root") as Node
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

When I run this `yarn start` and see console in the browser, here is what I see - 

![image](https://user-images.githubusercontent.com/2114206/84638764-439a1200-aeac-11ea-8b1d-0463b18386b6.png)

Using version `0.18.7` right now.

**Comment by ryansolid** [comment]
The reason this is happening is that dynamic props and `children` in Solid lazily evaluate so that they can be tracked properly in the reactive system. This means that the children are created on access. So early destructuring is causing the issue. You need to change your Component to:

 ```js
export const ContextProvider: Component = (props) => {
  console.log("Provider");
  return (
    <ExampleContext.Provider value={2}>{props.children}</ExampleContext.Provider>
  );
};
```
There is some talk about dynamic tracking at the top of the Component part of the docs but the children part isn't explicitly called out. I will update the docs.

**Comment by ryansolid** [comment]
Alright with the docs update and acknowledgement I'm going to close this one.
