### ISSUE TITLE
Question: How can I make createResource work in TypeScript?

### ISSUE THREAD

**Issue by milovanderlinden** [ryansolid/solid#184]
I am trying to port the [Data Loading](https://github.com/ryansolid/solid/blob/master/documentation/suspense.md#data-loading) example to Typescript. And although my fetch works, I cannot figure out how to grab the corresponding result. Besides that, typescript gives a whole bunch of errors in vscode, even though the code (partially works)

What am I doing wrong? Any advice is highly appreciated.

```typescript
import { createResource, Switch, Match } from "solid-js";

const fetchUser = async () => {
    const r = await fetch(`https://jsonplaceholder.typicode.com/todos/1`)
    const final = await r.json()
    console.log(final)
    return final
}

export const Ideas = () => {
    let [user, load] = createResource()

    load(fetchUser())

    return <div>
        <Switch fallback={"Failed to load User"}>
            <Match when={user.loading}>Loading...</Match>
            <Match when={user()}>{(i) =>
                <div>
                    Will something end up here?
                    {i.title}
                </div>
            }
            </Match>
        </Switch>
    </div>
}

```

**Comment by ryansolid** [comment]
Seems to be working for me: https://codesandbox.io/s/hungry-goldwasser-hijwd?file=/index.js

**Comment by milovanderlinden** [comment]
I tried to integrate your sandbox.

Yes, I have created the project with the starter. I looked at your sandbox, but I do not dare touching my tsconfig to much, yours has an entirely different config. Anyway, my project is here: https://github.com/milovanderlinden/idea-garden after running `npm i`, it should immediately run via `npm start`

**Comment by ryansolid** [comment]
Yeah that TSConfig is actually parcels default one.. I just put a strict true on it to see if I could see more issues. I'm actually looking at my Switch/Map code and I think regardless of the issue here I could improve the types some. I will give your repo a shot tonight.

**Comment by ryansolid** [comment]
Ok I think I figured it out. I only added using Switch/Match that way with functions in version 0.18.8.

Package.json only checks that the matched version matches the criteria. And package-lock has 0.18.7. So basically you need to update solid and I imagine it will work.

**Comment by ryansolid** [comment]
I verified it worked with that change in the project. Closing. If there is anything else let me know.

**Comment by milovanderlinden** [comment]
Testing it now, thank you so much for investigating!

**Comment by milovanderlinden** [comment]
I can confirm it works in 0.18.8, but breaks in 0.18.12. I am setting the requirement to be 0.18.8 exactly for now and will investigate why and at what version it breaks.

**Comment by ryansolid** [comment]
Try removing package-lock.json and update solid and Babel preset solid to latest. I will release update version of scripts with an latest tonight but more than likely it is version mismatching.
