### ISSUE TITLE
Cannot change component of <Dynamic> if its children is /*@once*/ and it has a sibling

### ISSUE THREAD

**Issue by boogerlad** [ryansolid/solid#185]
https://codesandbox.io/s/solid-dynamic-component-8ho84
remove `<div>broken</div>` and you will be able to change the component of `Dynamic`, as expected.

Click the button to change the component

**Comment by ryansolid** [comment]
Ok fixed in 0.18.11. Thanks for finding all of these. It's like adding null checks. Even though these cases are a little out there I feel the renderer is much more resilient for them.
