### ISSUE TITLE
Can't use Date Object in state?

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [ryansolid/solid#19]
Hello, for some reason this simple code (I use your Counter example) throw error when I'm trying to use Date Object method from Solidjs state:
```jsx
<html>
  <head>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <script src="https://unpkg.com/solid-standalone"></script>
    <script type='text/solid'>
      const { createRoot, createState, onCleanup } = Solid;
      
      const App = () => {
        const [state, setState] = createState({ counter: 0, dateTime: new Date() }),
          timer = setInterval(() => setState({ counter: state.counter + 1 }), 1000);
        onCleanup(() => clearInterval(timer));
        return <div>{( state.counter.toString() + ' ' + state.dateTime.toString() )}</div>
      }
      
      createRoot(() => document.body.appendChild(<App />));
    </script>
  </head>
  <body>
  </body>
</html>
```
Console error:
```
Uncaught TypeError: Method Date.prototype.toString called on incompatible receiver [object Object]
```
Maybe the method call isn't bound to the correct object?

**Comment by ryansolid** [comment]
Oh interesting. It doesn't recognize the Proxy as a Date object. I think it's likely I shouldn't be wrapping Dates in Proxies but you are correct, that it's not being bound to the right object.

I'm just trying to think where else this would apply. I do check if the value is a function on execution anyway so I could always bind functions but that seems perhaps incorrect to do in general.

I don't believe there are any downsides to not wrapping them. I'm not sure if change detection would work properly with mutating them. I think it's fair to treat them as immutable. Any opinions on how you'd expect them handled?

**Comment by ryansolid** [comment]
Decide to only wrap plain Objects and Arrays like MobX.
