### ISSUE TITLE
Make babel-preset-solid error if its version does not match solid-js?

### ISSUE THREAD

**Issue by mikeplus64** [ryansolid/solid#191]
Just ran into a hair-raising bug caused by mismatched versions, which is my fault, but it would be nice for `babel-preset-solid` to error if the two aren't at the same version. (Namely `solid-js@0.18.12` was subtly broken with `babel-preset-solid@0.18.7`)

**Comment by ryansolid** [comment]
Hmm.. I wonder how to best check. The compiler doesn't actually care or look at the library so it would have to be something in the compiled output that the runtime checks. More interesting is it isn't the preset that does it but the plugin which isn't tied to Solid specifically. So it would need to check again the babel plugin version. I wonder if I can version optional dependencies and have npm warn.

**Comment by ryansolid** [comment]
I tried optionalDependencies but it always installs. We want really optionalPeerDeps but those aren't a real thing with npm alone. Compile output is per file and not global so a lot of repeated work. I don't have a good solution for this right now.

**Comment by ryansolid** [comment]
I'm stumped and I've looked for a solution. I don't think there is a good one. I'm doing some house cleaning and I think this issue isn't going anywhere.

**Comment by mikeplus64** [comment]
Can `babel-preset-solid` not emit a constant like `const __solid_js_version = '0.19.3` and `solid-js` check that once inside `render`?

**Comment by ryansolid** [comment]
In every file? Compiler works on a per file basis.

**Comment by mikeplus64** [comment]
You'd emit it where `render` is called, or even add an extra argument to `render` for the `solid-js` version.
