### ISSUE TITLE
Cannot change component of <Dynamic> if its children is /*@once*/ and it has no siblings and the components return a fragment or (props.children or a fragment containing only props.children)

### ISSUE THREAD

**Issue by boogerlad** [ryansolid/solid#192]
https://codesandbox.io/s/solid-dynamic-component-89jvw
Click the button to change the component. Notice that the component and its children are gone now.
Also, https://codesandbox.io/s/solid-dynamic-component-pgxoz and https://codesandbox.io/s/solid-dynamic-component-xgskk show that it doesn't matter if there is no parent for dynamic, or if the parent is a real dom node, or if it's a fragment. still broken behavior. However, it works fine if `Dynamic` has a sibling: https://codesandbox.io/s/solid-dynamic-component-c2w9j

https://codesandbox.io/s/solid-dynamic-component-e7peo
By changing `ComponentB` to return a `span` instead of a fragment, clicking the button to change the component will change the component and its children will be retained.

**Comment by ryansolid** [comment]
Thank you it's pretty silly bug where I was trying to reduce DOM operations where replacing a fragment with a single node ends up replacing the first element but then it iterates to itself and removes itself.. I will fix this up tonight. Sorry this has been a bit tedious but this brings up a decent amount of scenarios that I don't hit often with basically manually moving the same children around different structures which doesn't normally happen in declarative flows.

**Comment by ryansolid** [comment]
Ok I fixed it in dom-expressions it will be a few days until I push out the next Solid release and will release it then.

**Comment by ryansolid** [comment]
Fixed in v0.18.13.
