### ISSUE TITLE
<use xlinkHref="..."/> rendered as <use xlink-href="..."/> instead of xlink:href

### ISSUE THREAD

**Issue by russelgal** [ryansolid/solid#193]
`<use xlink:href=".."/>` not working too
```ParseError: /src/components/icon/Icon.jsx
TypeError: /Volumes/sites/admin_solid/src/components/icon/Icon.jsx: attr.name.name.toLowerCase is not a function
 at /Volumes/sites/admin_solid/node_modules/babel-plugin-jsx-dom-expressions/index.js:1157:31

**Comment by ryansolid** [comment]
Fixed in 0.18.14 of solid and babel-preset-solid. Use the namespace form `xlink:href`

**Comment by dasDaniel** [comment]
I just came across this, and even though this has long been solved in `solid`, my VScode JSX formatter still yells at me for this.

You can also get around this by using ` {'<use xlink:href="..."/>'}`

**Comment by ryansolid** [comment]
I am hoping with TS adding support for JSX Namespaces in 4.2 that tooling will improve to support it. It might take some time if no one is using it.
