### ISSUE TITLE
Why ES6 Proxies?

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#2]
Could it be achieved with accessors, and therefore compatible with older browsers? Windows 10 still ships with IE 11, and I bet plenty of people are still not on IE 11.

Is there something specific that they are needed for?

Vue for example, uses getters/setters to make POJO-like simplicity.

**Comment by trusktr** [comment]
Thanks for that insight!

> You can technically use Solid renderer without the State object with S.js signals and it would be more performant (and be hard to tell apart from Surplus)

Interesting! Can you make a small example snippet of using signals instead of the state API?

**Comment by ryansolid** [comment]
This comment while conveying the same idealogical truth is now out of date with how it works in 0.3.x and above. People should refer to current documentation.
