### ISSUE TITLE
Custom npm module & computations warning

### ISSUE THREAD

**Issue by SanichKotikov** [ryansolid/solid#201]
Hi!

Trying to create own [npm module](https://github.com/SanichKotikov/simple-solid-router) for solid js. The code from src works will inside a project but when I extracted it as a module it starts showing `computations created outside a 'createRoot' or 'render' will never be disposed` warning.

Using:

```typescript tsx
import 'solid-js';
import { render } from 'solid-js/dom';
// using with npm link
import { RouterProvider } from 'simple-solid-router';

render(
  () => (
    <RouterProvider>
      <div/>
    </RouterProvider>
  ),
  document.getElementById('root') as Node
);
```

Could somebody help, what I'm doing wrong?

**Comment by ryansolid** [comment]
You need to make sure you don't have multiple versions of Solid. Make sure your package isn't including Solid in its own code.

Best practice is set solid-js as a peer dependency and set both solid-js and solid-js/dom as externals in your library's build process.

I intend to add some protection against that in the future or atleast a warning. If this isn't the issue let me know and we can brainstorm some more.

**Comment by SanichKotikov** [comment]
@ryansolid thanks, that's the answer!
