### ISSUE TITLE
`ref` ignored if syntactically looks like a value in some cases

### ISSUE THREAD

**Issue by mikeplus64** [ryansolid/solid#203]
I think this is a parser bug with `babel-preset-solid` and possibly the underlying lib it uses, but see https://codesandbox.io/s/ignored-ref-xsikh?file=/src/index.tsx

**Comment by ryansolid** [comment]
Yeah I was too specific in the non-assignable case to only look for functions. It should take every non-assignable statement and try to call it as a function instead. I know the fix will push it when able.

**Comment by mduclehcm** [comment]
@ryansolid Let's me fix this issue.
