### ISSUE TITLE
Wrong type annotation for double click event handler on JSX elements

### ISSUE THREAD

**Issue by Nedgeva** [ryansolid/solid#208]
JSX typings tells that there is "onDoubleClick" event handler: https://github.com/ryansolid/solid/blob/master/packages/solid/src/rendering/jsx.ts#L124
but in fact in runtime it's just ignores double click event with such key, so the only proper way to use double click event handler is to assign property to "onDblClick".

**Comment by ryansolid** [comment]
Fixed in release v0.19.0
