### ISSUE TITLE
The way to create no shadow root element

### ISSUE THREAD

**Issue by kmmbvnr** [ryansolid/solid#209]
is it possible to create no shadow root element?

`component-register` has  the function to override an element to bypass shadow root creation - https://github.com/ryansolid/component-register/blob/master/src/element.ts#L177

Is it possible to compose this withSolid?

**Comment by ryansolid** [comment]
Right now the options are 

1. To call the `noShadowDOM` function at the top of your component. Don't worry component only executes once per instance.
2. Write another middleware/mixin/composable function etc that sets `element.renderRoot = element` and put that in the `register` `withSolid` chain in between them. Something like (just writing this in here, untested):
```js
const withNoShadowDOM = (ComponentType) => {
    return (props, options) => {
      const { element } = options;
      element.renderRoot = element;
      return ComponentType(props, options);
    }
}

// And use it like
compose(
  register("my-comp"),
  withNoShadowDOM,
  withSolid
)(MyComp);
```
I probably should consider adding this `withNoShadowDOM` mixin to the component-register-extensions package.

**Comment by ryansolid** [comment]
Glad to help. Let me know if you have any other issues.

**Comment by Mojeer0** [comment]
With opt 2, because renderRoot is a getter we get the following error `TypeError: setting getter-only property "renderRoot"`

Here is a working version 

```
const withNoShadowDOM = (ComponentType) => {
    return (props, options) => {
      const { element } = options;
      Object.defineProperty(element, "renderRoot", {
        value: element
      });
      return ComponentType(props, options);
    }
}
```
