### ISSUE TITLE
A place for a Solid community ?

### ISSUE THREAD

**Issue by Yakulu** [ryansolid/solid#21]
Hello,

Solid seems really interesting to me and despite the articles, the documentation, I think there is a place missing for a nascent community, a place to exchange, discuss, question about the future of the framework, its use etc.

Such a space could well be a mailing list or a forum like Discourse... That said, perhaps the easiest way would be to create a Gitter chat room, directly related to code repositories? As an alternative, there are these Github issues, but I'm not sure that's appropriate. What do you think?

**Comment by athif23** [comment]
I agree, Gitter would be good, we can just use github account to login.

**Comment by ryansolid** [comment]
Ok, I have to admit this is an area I know absolutely nothing about. I could definitely see significant value in being able to ask questions and talk about these sort of topics outside of Github issues. I'm going to do a little research and see what I can pull together here quickly.

Thank you for your interest and the suggestion.

**Comment by ryansolid** [comment]
Ok looking at my options I think I like Spectrum. It has better separation of content and can sort of dual purpose. It has SSO with github so you can use your existing account.

I've created a community under https://spectrum.chat/solid-js

I will create a link in the Readme.

**Comment by Yakulu** [comment]
Thanks Ryan for your reactivity.
