### ISSUE TITLE
Portal wraps elements in div

### ISSUE THREAD

**Issue by MrFoxPro** [ryansolid/solid#210]
Hi. I want to insert some tags in head with Portal, but it's wrapping it into div. I found code here: https://github.com/ryansolid/solid/blob/c239a2b115f4a9e3797503c39890ceebb1a2a01e/packages/solid/src/dom/index.ts#L13

Could we use mount prop as container?

**Comment by MrFoxPro** [comment]
https://github.com/ryansolid/solid/pull/211

**Comment by ryansolid** [comment]
Added in v0.19.0
