### ISSUE TITLE
Equivalent getter to setState path?

### ISSUE THREAD

**Issue by Myrdden** [ryansolid/solid#215]
(Possibly related in purpose to #207)

Is there, or if not, could there be a getter function provided by createState that uses the same path syntax as setState?

If I have a situation like this,
```
<Widget get={state.something?.pathA?.pathB?.etc} set={(value) => setState('something', 'pathA', 'pathB', 'etc', value)}/>
```

It would be really nice to have a getter function with the same syntax such that I could write something like
```
<Widget data={['something', 'pathA', 'pathB', 'etc']}/>
```
and have the Widget component use the same path for it's getter and setter.

**Comment by ryansolid** [comment]
Interesting. I would have thought the first example preferable from the perspective that the `Widget` does not need to know anything state shape and just knows it can read a value and set a value. That being said a getter could be useful but it also doesn't require any library-specific support. I mean there are 3rd part FP libraries like Ramda. Without changing the way the state create tuple works all I'd be providing is something like:

```js
function getState(state, path) {
  const resolved = state;
  for (let i = 0, len = path.length; i < len; i++) {
    resolved = resolved[path[i]];
    if (resolved == null) break;
  }
  return resolved;
}
```

What might be more interesting is put them together.

```js
const etcLens = createLens('something', 'pathA', 'pathB', 'etc')
const [signal, setSignal] = etcLens(state, setState);
```

This wouldn't create an actual signal but it would function as one grant the ability to read and set a specific path. Not sure though that it saves much in terms of typing.

**Comment by Myrdden** [comment]
Ahh... Still don't know my way around reactivity that well... I'd intended to write a function like getState but I'd assumed that each `resolves[path[i]]` would've somehow triggered reactivity on each step or something... But, yeah, if I can just do something like that, then that would certainly work.

Also, the widget itself would still just have get and set and the pathing functionality would be provided by a HOC or something like createLens, ideally. I'd just simplified for the example.

**Comment by ryansolid** [comment]
I mean it does track along that path but I think that is desireable because if someone swapped out pathA you'd need to update. We have the ability to not track if desired. But need to understand the scenario a bit. I think as default we think tracking is fine. And it's only going to be tracked if executed under a tracking context. Again I think this is desireable but we have options.

**Comment by Myrdden** [comment]
So if I have a different widget which is... I don't know what you'd call that, lensed? Down to something like `['something', 'pathA', 'pathC', 'other']`, and I set `etc`, that won't do anything to the other widget because they're both down `pathA`? I'm possibly confused because I'm coming at this from a heavily ingrained React mindset...

**Comment by ryansolid** [comment]
Yeah it's because the downward propagation doesn't always happen by virtue of their being a change. There isn't a top-down execution necessarily on update. It naturally happens because parent conditionals will depend on state higher up the tree but generally speaking each reactive part is independent so in the end, it is fairly flat. So it needs to track its path. But you get partial paths naturally from having the DOM hierarchy (ie propagation through props). In practice it means when it comes to state/props you want to generally access from the top level in your scope to the data you need under a reactive context. It happens naturally in bindings.

If you take a mentality of defer property access to the last moment (which is true for Vue and MobX too) you will be fine. If you are in a "hook" or JSX write the code as normal and it should work out. The reactive system at runtime will prevent duplicate executions.. so even if 4 different reactive atoms are posting their changes at the same time they will only run once.

**Comment by Myrdden** [comment]
Ok, so, last question... My plan is to implement essentially a createLens hook of sorts, ideally it should have all the same pathing functionality that setState does, but I know that destructuring can (maybe just under specific circumstances) cause tracking to be lost. So, if I implement a filter just using array.filter, will calling that break reactivity? I would guess if something like `resolved = state` doesn't break reactivity an array filter wouldn't either, but I figured I'd cover my bases before digging myself too deep a hole.

**Comment by ryansolid** [comment]
Your function should return a getter and setter function. So you don't have to worry about reactivity so much. The person calling it will have to decide whether to execute it under a reactive context. It depends completely on where they call your getter. I imagine in most cases that will be in a binding. Basically to the consumer it looks like a signal. They should follow the rules for signals if they want it reactive.

**Comment by Myrdden** [comment]
I have a function `getState` which looks exactly the same as `setState`, except without the last argument, which returns wherever the path leads. Will this not work?

**Comment by ryansolid** [comment]
The property access decides reactivity. So I'm just suggesting something like this:

```js
function createSomething(state, setState, path) {
  return [
    () => {
      const resolved = state;
      for (let i = 0, len = path.length; i < len; i++) {
        resolved = resolved[path[i]];
        if (resolved == null) break;
      }
      return resolved;
    },
    (value) => setState(...path.concat(value));
  ]
}
```

**Comment by Myrdden** [comment]
I'm using a context, basically this:
```
const Provider = (props) => {
  const [store, set] = createState();
  const get = (path) => {
    let obj = state;
    // lensing stuff.
    return obj;
  }

  return <StoreContext.Provider value={{get, set, store}}>{props.children}</StoreContext.Provider>;
}
```
Used like:
```
const {get, set} = useStore();
const someData = get([path]);
return <p>{someData?.text}</p>;
```
If I'm understanding you correctly, this should be good... Provided there's nothing glaringly wrong with this, I guess that answers my question.

**Comment by ryansolid** [comment]
I'm suggesting that this is good:

```jsx
const {get, set} = useStore();
return <p>{ get([path])?.text}</p>;
```

Or this:

```jsx
const {get, set} = useStore();
const someData = () => get([path]);
return <p>{someData()?.text}</p>;
```

The getter should be called inside the reactive context most likely.

**Comment by Myrdden** [comment]
Ahhh, OK. I think I get it now. So, a reactive context is not any component function body, but rather specifically within a memo, effect or JSX?

**Comment by ryansolid** [comment]
Yes they are not. I made components untracked as it would be very inefficient if someone ever triggered it as it would re-render everything in the component. Or worse everything in the parent reactive context it is a part of (say it was in a conditional). Component is just a function call. `<Component />` = `Component()`. Nothing extra.. With props there is some dynamic wrapping but even those in themselves don't create any additional signals or effects. Therefore components are lightweight. They have almost no overhead other than breaking apart contiguous template (has an effect on how many DOM nodes are cloned at a time).

Even the creation of `<p>` is outside of a reactive context we just wrap the expression.

It's easier to see with the compiled output. This intro article might be the best way of seeing what is going on more or less: https://dev.to/atfzl/understanding-solid-jsx-584p
