### ISSUE TITLE
Improve createMemo's signature

### ISSUE THREAD

**Issue by Koxiaet** [ryansolid/solid#216]
Currently `createMemo`'s signature looks like:

```typescript
export declare function createMemo<T>(fn: (v?: T) => T, value?: T, areEqual?: boolean | ((prev: T, next: T) => boolean)): () => T;
```

By adding two more signatures the relationship between `value` and `v` can be better shown:

```typescript
export declare function createMemo<T>(fn: (v: T) => T, value: T, areEqual?: boolean | ((prev: T, next: T) => boolean)): () => T;
export declare function createMemo<T>(fn: (v?: T) => T, value: undefined, areEqual?: boolean | ((prev: T, next: T) => boolean)): () => T;
```

**Comment by ryansolid** [comment]
I very much welcome TypeScript PRs as my experience tends to be whatever I try never works and spend hours wasting my time on something someone else could solve simply. I tried to get it to work but a bunch of tests complained and I didn't figure it out.
