### ISSUE TITLE
Type unsafety in createSignal

### ISSUE THREAD

**Issue by Koxiaet** [ryansolid/solid#217]
`createSignal`'s signature has type unsafety when initialized without arguments:

```typescript
const [value, set_value] = createSignal<number>();
value(); // This is `undefined`, but its type says that it's a number.
```
It's a rather small issue, but it can cause bugs.

**Comment by ryansolid** [comment]
I very much welcome TypeScript PRs as my experience tends to be whatever I try never works.

**Comment by Koxiaet** [comment]
So fixing this while still supporting the no argument syntax requires changing the type signature to:

```typescript
export function createSignal<T>(
  ...args: (T extends undefined ? [] | never)
    | [T, (boolean | ((prev: T, next: T)) => boolean)?]
): [() => T, (v: T) => T] {
```

When Typescript 4.0 comes the named parameters will come back, but for now this is the only solution (unless I'm missing something obvious).

**Comment by ryansolid** [comment]
I'm with it if it makes sense but I was having trouble making this one work with the tests as well. Honestly, I wish there was another way. It's too bad that this sort of optional parameters that affect generics have this issue. There is a difference of `T` undefined and it being optional. Maybe we do leave this until TS 4.

**Comment by ryansolid** [comment]
Thanks @Gustorn this looks to more or less work.
