### ISSUE TITLE
[enhancement] library name enhancement

### ISSUE THREAD

**Issue by samadadi** [ryansolid/solid#226]
Hi. I love solid library and I love the name "solid". I think there is a consistency problem in libraries names and importing functions from those. For example I can import most of the function from "solid-js/dom" librarary and I can do the same with "solid-js" library so why not have a single library that exports all functions. Or we can have two separate library that each of those exports its specific functions. And here is my suggestion for library names:
solid-js         --->     solid
solid-js/dom --->     solid-dom
solid-rx --->  good
solid-ssr --->  good
solid-element --->  good
dom-expressions --->  solid-dom-expressions
solid-styled-components --->  good
solid-hot-loader --->  good

**Comment by ryansolid** [comment]
I understand where you are coming from although things are thus way for a few reasons. Firstly `solid` was already taken on npm so without namespacing which is even more verbose I needed a different name.

The DOM Expressions library serves multiple libraries. It is not Solid specific. As I update it I can update all the libraries. It drastically simplifies things to pull all automatically included deps from a single module as understandably each library might have things in different places. Why this even exists is so we can only import the code we need based on the features you use. This allows tree shaking to make the smallest bundles 

Now the DOM is only a single target. There is also Server rendering and potentially in the future mobile, or even custom canvas or WebGL renderers. The same reactive core can be used by all of these, including the component model and a lot of the control flow patterns. However sometimes different targets require custom implementation like say Dynamic or Portal. I use the different builds as a way to override core behavior.

Now I could compile these all into completely different bundles with the fully included reactive runtime but I thought it would be better to follow the React pattern of having the single core library. Solid behaves very poorly with multiple copies of it around and without predicting how people are going to use it I think that is desirable.

**Comment by ryansolid** [comment]
That all being said I might split off the dom and server libraries into their own modules. Most of the reason I left them is they require almost identical build processes and while I've been refining the boundary between the libraries I've been moving things back and forth a fair bit. In any case. Point noted but I think no action in the near term. Thanks for the suggestion. Will keep this in mind as things progress.
