### ISSUE TITLE
Non-selling example in the readme

### ISSUE THREAD

**Issue by frenzzy** [ryansolid/solid#227]
Hello! I'm not familiar with solid.js yet but the description looks cool! I would like to share my first impression after reading the readme. I hope this makes the world a better place :)

Example from readme:
```js
import { createState, onCleanup } from "solid-js";
import { render } from "solid-js/dom";

const App = () => {
  const [state, setState] = createState({
    user: {
      firstName: "John",
      lastName: "Smith",
      get fullName() { return `${state.firstName} ${state.lastName}`; }
    }
  });

  return (
    <div
      onClick={() => setState("user", "lastName", l => l + "!")}
    >{state.user.fullName}</div>
  );
};

render(() => <App />, document.getElementById("app"));
```
1. It is not clear how `firstName` gets inside` state`. It looks like a typo, maybe you meant `state.user.firstName` or `this.firstName` instead?
    <img width="506" alt="Forgot user?" src="https://user-images.githubusercontent.com/640669/92255073-7b788a80-eeda-11ea-9ce0-66f89d42c082.png">

2. Is solid.js really typescript friendly? How it prevent consumers from typos and mistakes during refactoring?
    <img width="434" alt="TypeScript compatibility question" src="https://user-images.githubusercontent.com/640669/92255445-0063a400-eedb-11ea-9c87-1a773dd3e9c2.png">

3. What `l` means? Should it be `value` instead?
    <img width="434" alt="Incomprehensible variable name" src="https://user-images.githubusercontent.com/640669/92255837-8e3f8f00-eedb-11ea-9a00-1e644586a9cd.png">

4. Code formatting. It takes just a moment to copy paste a code snippet into an IDE like VSCode and apply formatting (usually [prettier](https://prettier.io/) is a default formatter). When you look at the formatted samples in the documentation, you feel like you've been taken care of, it is so cool!

Thank you so much for your incredible work! I wish popularity and prosperity to this project, peace ✌️

**Comment by ryansolid** [comment]
Thanks. I added getters in state this past week and clearly updated the example while half asleep. `l` was `lastName` but no way it's obvious. I will get that fixed up.

As for TypeScript I have to admit it's been a big effort of the community. I honestly thought the state setter was untypable but they proved me wrong. I can't vouch to it being perfect but my understanding is it generally works giving you path completion.
