### ISSUE TITLE
What does createEffect do?

### ISSUE THREAD

**Issue by YeskaNova** [ryansolid/solid#230]
Hi,

First of all, thanks a lot for this amazing work!

I'm prototyping some personal projects, and I want to try Solid. I can see in some code snippets the function createEffect ( like in https://codesandbox.io/s/2o4wmxj9zy?file=/index.js:317-329 ). What does it do exactly? I have tried removing it and it still works as expected.

**Comment by ryansolid** [comment]
It shouldn't unless something is self-propelling like setInterval or a setTimeout loop. `createEffect` is a way of indicating that the code is being tracked (ie, it re-runs when reactive signals inside are updated), and that this code produces side effects. Sometimes code sandbox has multiple copies of Solid bound to the elements at the same time which can cause some very confusing behavior. So it's possible that on edit the effect was still there in the background and a refresh would remedy that.

**Comment by YeskaNova** [comment]
I see. I confirm that in the example, without createEffect the user info does not load ( it worked in my code because I wasn't changing the data after the loading ). Thank you it's all clear now :).
