### ISSUE TITLE
npm init

### ISSUE THREAD

**Issue by herzaso** [ryansolid/solid#235]
When initializing a project through `npm init solid app my-app`, there are many references to React / CRA (README.md, index.js, etc.)

**Comment by ryansolid** [comment]
To be fair CRA has good docs to the functionality. I don't know half the things it does. So pointing to CRA docs makes a lot of sense. Not sure how realistic it is to remove this and replace.

**Comment by ryansolid** [comment]
I'm closing this as no action for now.
