### ISSUE TITLE
nested component with split children

### ISSUE THREAD

**Issue by vemoo** [ryansolid/solid#238]
Given this code:
```typescript
function App() {
    return (
        <Splitter name="outer">
            <Splitter name="inner">
                <div>11</div>
                <div>12</div>
            </Splitter>
            <div>2</div>
        </Splitter>
    );
}

function Splitter(props: {
    name: string;
    children: [JSX.Element, JSX.Element];
}) {
    console.log(`Splitter "${props.name}"`);
    return (
        <>
            <div>{props.children[0]}</div>
            <div>{props.children[1]}</div>
        </>
    );
}
```
I would expect console output to be:
```
Splitter "outer" 
Splitter "inner" 
```
but it's:
```
Splitter "outer" 
Splitter "inner" 
Splitter "inner" 
```
[codesandbox link](https://codesandbox.io/s/repro-e5i2u?file=/index.tsx)

**Comment by vemoo** [comment]
using `createMemo` seems to fix it
```typescript
function Splitter(props: {
    name: string;
    children: [JSX.Element, JSX.Element];
}) {
    console.log(`Splitter "${props.name}"`);
    const children = createMemo(() => props.children);
    return (
        <>
            <div>{children()[0]}</div>
            <div>{children()[1]}</div>
        </>
    );
}
```
but I'm not sure I understand why

**Comment by vemoo** [comment]
I think the issue happens when `props.children` is used more than once, because if I do this:
```typescript
function Splitter(props: {
    name: string;
    children: [JSX.Element, JSX.Element];
}) {
    console.log(`Splitter "${props.name}"`);
    createEffect(() => {
        console.log(props.children);
    });
    const children = createMemo(() => props.children);
    return (
        <>
            <div>{children()[0]}</div>
            <div>{children()[1]}</div>
        </>
    );
}
```
the issue appears again

**Comment by ryansolid** [comment]
Yes, what you are witnessing is that `props.children` is lazy evaluated. As are any prop expression that returns JSX. Like the `fallback` on control flow. At that point it is the same as any dynamic prop so any access reruns the wrapped code. Ie recreating the elements.

https://github.com/ryansolid/solid/blob/master/documentation/components.md#children

If the children are always static accessing them into a temporary variable works or if dynamic a memo like you were doing.

**Comment by vemoo** [comment]
Thank you for the explanation, that makes sense. My original issue was the way it interacts `ref`s: [link](https://codesandbox.io/s/repro-forked-0fp97?file=/index.tsx).

I guess it could be usefull to write some lint rules for this kind of issues, but for now I will read the documentation more carefully :wink:
