### ISSUE TITLE
Suppressing warnings when computations created outside

### ISSUE THREAD

**Issue by luncheon** [ryansolid/solid#242]
Thank you for creating the great package!
I have a question.

`createSignal()` and `createState()` can be used at the top level of a module. Returned getter and setter can be shared by multiple components.

`createMemo()` can also be used at the top level and can be shared, but it outputs a warning to the console.

> computations created outside a `createRoot` or `render` will never be disposed

I think it's a normal use case to share memoized computed values. That's why [Reselect](https://github.com/reduxjs/reselect) or [Recoil.selector()](https://recoiljs.org/docs/basic-tutorial/selectors) exist. And developers would understand the top level effects will never be disposed. They are application-level effects.

Also, I think `createEffect()` at the top level is a normal use case (e.g., logging).

So, could you provide a way to suppress the warning? Or does it not fit your design philosophy?

```js
const [count, setCount] = createSignal(0);

// warning
const doubleCount = createMemo(() => count() * 2);

// error
createEffect(() => console.log(count()));

// warning
createRenderEffect(() => console.log(count()));
```

https://codesandbox.io/s/solid-warning-rrqii?file=/index.tsx

**Comment by ryansolid** [comment]
Yeah that's tricky. I've created a reactive system with automatic disposal. The observer pattern leaks when the atom being observed outlives the subscriber. Subscribers need to be released. So I have each nested layer manage the ownership of its children. By creating a single top-level computation that tracks ownership I can contain everything and its ducks all the way down so to speak. At first, that was the extent of it, but this reactive graph is also the source of Context (has nothing to do with Components or view), and ultimately as a mechanism for ensuring execution order as everything is synchronous.

The recommended approach is to use Context API. There is no performance overhead unlike React and it gives clear ownership in terms of the reactive graph. The hierarchy naturally memoizes and this just makes it all part of the same system. So a top-level Provider more or less gives you this. But this pattern works well all the way down the render tree. It's consistent and repeatable. Modular for things like testing.

I can see that if you don't care about these you might think to make it top-level. However, effects always queue to the end of the update cycle and if it is created outside of a reactive context there is no queue. That leaves either running immediately (inconsistent behaviour) or throwing a more specific error or warning. Honestly, I can't guarantee what other features may be compromised in the future.

To be fair the core pieces, signal/state, memo, computed will work fine outside of a root. The whole effect thing is a scheduling thing and doesn't really have meaning outside of render-tree. `createComputed` is the more direct equivalent to say MobX's `autorun`. You can also manually create a root with `createRoot` call but that is a bit clunky.

**Comment by luncheon** [comment]
Thank you for the explanation.

> The recommended approach is to use Context API.

Yeah, but I want dead simple APIs like `createSignal()` or `createMemo()`. Context API is a bit cumbersome.

> To be fair the core pieces, signal/state, memo, computed will work fine outside of a root.
> `createComputed` is the more direct equivalent to say MobX's `autorun`.

Thanks. Good news for me. But the warning is distressing...

Then, I realized that what I needed to do may be to delay the global process until the root component initialization.

```tsx
const global = new GlobalContext();

// register `createSignal()` calllback
const [count, setCount] = global.signal(0);

// register `createMemo()` callback
const doubleCount = global.memo(() => count() * 2);

// register `createEffect()` callback
global.effect(() => console.log(count()));

const App = () => {
  // dispatch each registered callback
  global.bootstrap(); // all registered setup 
  return <>...</>
}
```
https://codesandbox.io/s/lmrb9?file=/index.tsx

If you have any thoughts, please let me know.

Thank you.

**Comment by ryansolid** [comment]
The warning is there to prevent people from doing things unwittingly. I see it happen sometimes in event handlers, promise resolutions etc. Places where they don't realize they are creating things outside of a reactive context and that they could be just creating big memory leaks. Truthfully I don't have much in the way of global configuration. No dev mode yet etc so I currently don't have a mechanism to suppress warnings. 

What you did works nicely. Register the methods on a singleton module and initialize on app startup. The reactivity will only last for as long as the app exists but I imagine that is perfectly fine. By doing so under the same tree as the application you are connecting the scheduling of effects etc to the right timing so that should work very similar to a top-level provider in terms of execution.

**Comment by luncheon** [comment]
I see. I understand the reason for the warning. And I'm relieved that my approach seems to work.
Thank you very much.
