### ISSUE TITLE
Question regarding the support of Flow lang or ReasonML/ReScript

### ISSUE THREAD

**Issue by gaku-sei** [ryansolid/solid#245]
I really love this framework and plan to use it for some middle sized project, but using TypeScript is a bit of a letdown to me 😞 

Is there any (planned) support for Flow lang or ReasonML (official or unofficial)?

It feels like ReasonML _could_ be supported somehow but I wonder how some features, like currying, would work with the Solid "transpiler" 😕

**Comment by ryansolid** [comment]
Well it's only the JSX that is transpiled. And it is a very custom compilation. One that I suspect would not be supported by ReasonML, but I'm not 100% on that. The way it works cannot be reduced into simple function calls and I morph not just the elements but the attributes as well. That being said I do have support for HyperScript with a bit of manual work. It doesn't leverage most of the benefits of the JSX compiler but it does have the advantage here of boiling down to a simple `h` function. So from that perspective there could be a version where you manually wrap your expressions and the integration could generally be the same as library like Preact. Although the HyperScript is less mature and doesn't support SSR yet etc and is just for the browser.

I have no knowledge of ReasonML and not being able to leverage the custom transforms definitely would dampen my enthusiasm for such an approach. But it definitely isn't off the table. I'm not aware of anyone working on this as of yet.

**Comment by gaku-sei** [comment]
Thank you very much @ryansolid 

>Well it's only the JSX that is transpiled.

That's very good to know, if only the jsx code is transpiled, it means compiling OCaml/ReasonML to JS _and_ preserving the jsx _could_ work. I might give it a try soon. I think I read somewhere it was doable, but I couldn't find the documentation (yet). 

I will give it a try as soon as possible, and try to report here if I can make it work somehow 😄

**Comment by d4h0** [comment]
Something like Solid or Svelte for ReasonML would be fantastic! :)

@gaku-sei: as far as I remember, you just can embed JavaScript into Reason. But I'm not sure if Reason would allow JSX there. Even if it does, however, JSX isn't valid JavaScript, so you'd have to compile the output from Reason to JavaScript (so basically, there would three compile phases with Solid, which probably isn't great).

The easiest approach probably would be to just put Solid code into a separate `.js` file and import things from Reason.

@ryansolid: You should have look at ReasonML/OCaml. I think it's a fantastic language (in many ways better than TypeScript). I would be astonished if you don't like ReasonML/OCaml, to be honest.

**Comment by gaku-sei** [comment]
@d4h0 
>The easiest approach probably would be to just put Solid code into a separate .js file and import things from Reason.
This seems to be indeed the easiest approach so far 😕 

After trying a bit yesterday, i could make this Gist and it _partly_ works: https://gist.github.com/gaku-sei/8e1d157682379d2bafc4b6dc4e080091

So far, here are some notices:
- We must use the [uncurried function syntax](https://www.oreilly.com/library/view/reasonml-quick-start/9781789340785/2ec07646-e729-4bc8-84fd-444e3428c2fd.xhtml)
- It seems JSX cannot be preserved when compiling down to JS (I opened this issue: https://github.com/rescript-lang/rescript-compiler/issues/4783)
- But we can use hyperscript (provided we write a ppx for it ^^)
- The rest seems to be work ok, since as @ryansolid noticed, the Solid compiler doesn't transform anything else.

**Comment by ryansolid** [comment]
Well that's good. HyperScript means you need to wrap expressions in functions yourself but otherwise should work. This is pretty exciting. There is definitely some interest here, I've just do not have experience with ReasonML. I have some examples.. There is a TodoList example in the examples section. See it here: https://codesandbox.io/s/0vmjlmq94v
