### ISSUE TITLE
Update peerDependency version in solid-styled-jsx

### ISSUE THREAD

**Issue by alker0** [ryansolid/solid#257]
Solid-styled-jsx v0.21.5 specifies `solid-js: ^0.18.0` in package.json peerDependencies. It seems to mean `>= 0.18.0 < 0.19.0`, and yarn v2 shows peerDependency warning when using latest Solid.

**Comment by ryansolid** [comment]
I see minor version 0.x.x work differently. That's a hassle. I will look to keep that up to date in the future.

**Comment by alker0** [comment]
It is ok. Thank you.
