### ISSUE TITLE
How to use goober-autoprefixer with solid-styled-components?

### ISSUE THREAD

**Issue by isakkeyten** [ryansolid/solid#265]
Basically title,

in solid styled components the setup is hidden so how do we inject their autoprefix option?

Thanks

**Comment by ryansolid** [comment]
Yeah I just bumped the version recently as it fixed some bugs. I didn't notice they had added a few new features. I will look into what it will take to get those supported.

**Comment by ryansolid** [comment]
Ok I'm going to pass a version of the `setup` function through that only takes the prefixer. I thought about making it just a prefix function but this leaves me open for whatever other features adds in the future.

**Comment by isakkeyten** [comment]
Awesome, thanks Ryan

**Comment by ryansolid** [comment]
Nvm.. releasing right now. You should see it in a couple mins.
