### ISSUE TITLE
Solid SSR Main Field Index.js Does Not Exist

### ISSUE THREAD

**Issue by shadowtime2000** [ryansolid/solid#266]
In the `solid-ssr` package, the `main` field of `package.json` is `index.js` and the `types` field is `index.d.ts` both of which do not exist. This causes errors when you `require()` it in NodeJS.

**Comment by ryansolid** [comment]
Hi,
I haven't been particularly transparent with my intention for this library. It was designed to be a bunch of helper libraries to support SSR. However some of the older ones were removed, and I haven't written more. It's not necessarily my intention to make the SSG the default export for the full package. I believe it should work today with `require("solid-ssr/static")`. Still just working through what this will all look like.

**Comment by shadowtime2000** [comment]
What about allowing people to do `const { static } = require("solid-ssr");` or something like that?

**Comment by ryansolid** [comment]
It's setting the core modules API surface. It's unlikely this becomes a single module. Until I've worked that out I'd rather not. I'm working on a more substantial SSR example/build setup. I'm going to figure that out before I consolidate here and write some much-needed documentation.
