### ISSUE TITLE
Issue when component named Switch

### ISSUE THREAD

**Issue by phungleson** [ryansolid/solid#268]
I am using app created by `solid-scripts`

I created a component named `Switch` basically a `button` with some iOS UI.

I renamed to `ButtonSwitch` then it works, I have checked and am sure I use my `Switch` instead of one from `solid`

![image](https://user-images.githubusercontent.com/93457/100445668-99ccdb80-3101-11eb-80f7-e168b3aecfdc.png)

**Comment by boogerlad** [comment]
"Control flows can be imported from solid-js but as a convenience the compiler will automatically import them from solid-js/web"
https://github.com/ryansolid/solid/blob/11fc3df98bea7d8b49879b8a5ce98aacaca4bfd2/documentation/rendering.md

**Comment by ryansolid** [comment]
Yeah. Existing control flow components are treated almost as if reserved. In template DSL it is common not to have to import helpers and I followed suit. Mind you TS doesn't let me do this. Maybe I can look at detecting if the name has already been imported and skip it. The current solution aliases and doesn't conflict if you have something else called Switch but it apply the built in control flow always.

**Comment by ryansolid** [comment]
Yeah wasn't too hard to fix. I fixed this Babel Plugin JSX DOM Expressions 0.23.5. I didn't do a Solid release as of yet but it matches the dep range so if you blow out any package locks it should work.

The new behavior is that if the var is already detected in scope it won't import it.

**Comment by phungleson** [comment]
Alright thanks guys, cheers
