### ISSUE TITLE
"Getting Started" does not work out of the box because of outdated postcss dependencies

### ISSUE THREAD

**Issue by christian-fuss** [ryansolid/solid#274]
Following the "Getting Started" for a fresh install (of app-ts with neither npm nor yarn), the setup does not work out of the box, because the `postcss` dependencies are outdated:

```bash
> npm init solid app-ts my-app
# or
> yarn create solid app-ts my-app

$ solid-scripts build
Creating an optimized production build...
Failed to compile.

./src/index.css
Error: PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

Manually adding `postcss` and `postcss-loader` in version 8 as devDependencies fixes the issue.

**Comment by ryansolid** [comment]
Thanks for reporting. Strangely enough I didn't see this when I did an install after the update. Seem to be on the latest postcss-loader in the package.json. I believe they are on 4.1.0. I don't believe I was ever directly setting postcss as a dependency. 

It could help if you could provide a little more information. Is this a new create install or a package update where you are seeing this? Are you using npm or yarn?

**Comment by christian-fuss** [comment]
Hi Ryan, I updated my initial comment. I am completely new to SolidJS and trying it out right now, coming from 2.5 years full-time React. It looks really cool so far.

I tried to figure out, where the dependency to the postcss 8 came from, but due to so many dependencies to it in the yarn.lock I did not see it right away. I just searched for it now and it seems to be the postcss-safe-parser and the postcss-preset-env that are transitively required by the solid-scripts.

**Comment by ryansolid** [comment]
Yeah these sort of dep issues go beyond the framework and are "fun" for everyone. This is all resultant of this: https://github.com/ryansolid/solid-scripts/issues/15. Thanks for the information I will play with some stuff and try to get it out this evening.

**Comment by ryansolid** [comment]
Ok should be fixed in the latest version that I just published. I think my mistake was not doing a clean install to test. Because the previous version worked fine on upgrade. I've done a clean install now with my fix and it looks good. I will close now but if you hit any issues please report or reopen if applicable.

**Comment by christian-fuss** [comment]
Yep. Just tried it out. Works great now. Thanks for the quick response.
