### ISSUE TITLE
Missing "type" field in package.json

### ISSUE THREAD

**Issue by pavulon** [ryansolid/solid#277]
I've been toying around with SSR and found an issue:

When running server as an ES module, since `solid` and its subpackages don't include `type: "module"` in their package.json files, node recognizes them as CommonJS modules. This makes using named imports from solid throw errors like
```
SyntaxError: Named export 'ssr' not found. The requested module 'solid-js/web' is a CommonJS module, which may not support all module.exports as named exports.
```
Judging by `.js` and `.cjs` pairs in the [`exports` field](https://github.com/ryansolid/solid/blob/ba6bf662ad766d4245ae99acbac9c7cc6e75e916/packages/solid/package.json#L29), I guess treating `.js` files as ES modules was the intention, but this problem wasn't caught since examples compile everything to CommonJS.

By the way, some packages contain `.cjs.js` files in their `dist` folders. Not sure if intentional, but looks like a mistake.

**Comment by ryansolid** [comment]
Yeah right, I didn't even pick up that because of the way they are compiled. Thanks for pointing it out. I've been doing a lot of changes here in recent releases so I haven't migrated all the libraries over. I used to use `.cjs.js` as a way of indicating cjs (similar to preact) so it's possible I haven't moved all libraries over but I will do an audit and fix up any missing ones. Thank you.

**Comment by pavulon** [comment]
I think this needs to be set in other package.json files as well, because as the [docs state](https://nodejs.org/api/packages.html#packages_determining_module_system):
>Node.js will treat as CommonJS all other forms of input, such as `.js` files where the nearest parent `package.json` file contains no top-level `"type"` field

and that's what my simple tests confirm. For a simple package:

```
{
  "name": "test",
  "type": "module",
  "dependencies": {
    "solid-js": "^0.23.0"
  }
}
```
and input file
```
import { For } from "solid-js";
import { renderToString } from "solid-js/web";
```
running will result in an error, until I add `type: "module"` to both `node_modules/solid-js/package.json` and `node_modules/solid-js/web/package.json`.

Adding it only to `node_modules/solid-js/package.json` and removing `node_modules/solid-js/web/package.json` completely also helps, as you'd expect, but this might break some bundlers. In fact, it didn't work with rollup until I've updated `node-resolve` plugin to the latest version with `exports` support, which was released like week ago.

***

Also
```
$ find . -type f -name '*.cjs.js'
./node_modules/solid-js/html/dist/html.cjs.js
./node_modules/solid-js/h/dist/h.cjs.js
./node_modules/solid-js/dev/dist/dev.cjs.js
```
I don't think they break anything, just thought it was worth mentioning.

**Comment by ryansolid** [comment]
Yeah the nested package.json help with older non-export map environments. I can add type module there too. Good call.

> ./node_modules/solid-js/html/dist/html.cjs.js
./node_modules/solid-js/h/dist/h.cjs.js
./node_modules/solid-js/dev/dist/dev.cjs.js

Ah yes .. I see remnants from a previous build. When I changed the build pattern the cleanup stopped cleaning the folder even though they aren't generated anymore.
