### ISSUE TITLE
Provide react-solid-state typings

### ISSUE THREAD

**Issue by mneumann** [ryansolid/solid#278]
I'd like to use `react-solid-state` in a React/Typescript project, but the typing are missing. Or do I have to import the types from `solid`?

**Comment by ryansolid** [comment]
Yes, they are just absent. I implemented the project in JS, and the TS migration was driven by the community initially so I never got around to converting the project to TS. I suppose providing a .d.ts would be easy enough as well. It just hasn't been priority.

**Comment by ryansolid** [comment]
Fixed in #295. And released in 0.23.7. Let us know if you hit any issues. Cheers.
