### ISSUE TITLE
JSX Type Definitions

### ISSUE THREAD

**Issue by thatcort** [ryansolid/solid#282]
I just created a new Solid app with the create script and VSCode is complaining about missing JSX types:

`JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.`

I see this was addressed in #33 , but the proposed solution doesn't seem to work. The babel-plugin-jsx-dom-expressions library does not contain type definitions. Is there a new proposed solution for this issue?

**Comment by ryansolid** [comment]
Yes. In the latest version of Solid, we changed to the new mechanism for exposing JSX types. Back in #33 we were doing an explicit import, I switched to global JSX like React and Inferno. However, that doesn't allow multiple JSX providers in the same project. In TypeScript 4.1.1 they added the ability to set it in proper non-contaminating way via `jsxImportSource`.

The starter automatically adds this. However VSCode might not be using the workspace's TypeScript version. You can tell this by looking at the bottom of your window. You might see something like `4.0.3`. If you click on it you will have options. You want to select the workspace version which I believe will be 4.1.3. That should instantly fix the TypeScript resolution.

There is a guide here: https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript

**Comment by haglobah** [comment]
In case you've come here because you got this error message after 2021, make sure you don't have any typos in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```

:)
