### ISSUE TITLE
Enable GitHub discussions

### ISSUE THREAD

**Issue by aminya** [ryansolid/solid#285]
It would be nice if you can enable GitHub discussions. That would be a nicer place to discuss things compared to issues. 
Personally, I am looking for a place that we can share solid components and ask questions without disturbing the flow of the development (by creating issues).

A good portion of previous issues has been questions that would have a better place in the discussions.
https://github.com/ryansolid/solid/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+label%3Aquestion

**Comment by ryansolid** [comment]
Seems reasonable given strong tie back to github. I spend most of my time on the Discord, so only real question is if it splits things and determine what the overlap is.

**Comment by aminya** [comment]
The discussions in the chat apps like Discord or Slack are forgotten or lost. But GitHub Discussions always remain there which can make them different. Having Discord for informal chatting is still useful, but organized forum-like discussions are more productive for a community.

**Comment by ryansolid** [comment]
I do miss that aspect after we moved off Spectrum. I will flag the guy in charge of the community side.

Hey @davedbase give this a look and tell me what you think.

**Comment by ryansolid** [comment]
Thank you @aminya it is done. I think this will help a lot with those common questions that don't belong as issues.
