### ISSUE TITLE
Question: component doesn't update when property changes

### ISSUE THREAD

**Issue by romgrk** [ryansolid/solid#287]
Hi,

First experience with solid, sorry if the question seems trivial. I have a component that passes a state value to another component as a prop. However the inner component (`Button` in the example above) doesn't update when the state value changes and I don't understand why.

```javascript
function App() {
  const [state, setState] = createState({ progress: 0 });
  const timer = setInterval(() => setState({ progress: (state.progress + 1) % 100 }), 50);

  onCleanup(() => clearInterval(timer));

  return (
    <div class='App'>
        <Button progress={state.progress}>
            Progress Button
        </Button>
    </div>
  );
}

function Button({ children, progress }) {
  return (
    <button class='Button' data-progress={progress}>
      {children}
    </button>
  )
}
```

DOM value for `data-progress` stays at `0` :/ 
However if I use `state.progress` in the text of the children of `Button` as below, the text does update...but `data-progress` stays at `0` :/ 

```js
  return (
    <div class='App'>
        <Button progress={state.progress}>
            Progress Button {state.progress}     <------ This updates
        </Button>
    </div>
  );
```

**Comment by ryansolid** [comment]
No problem. And there is luckily an easy solution. Unfortunately you have run into the likely biggest gotcha with the approach Solid uses. This is shared by Vue and MobX too. We can't destructure props without losing reactivity. The button component needs to look like:

```jsx
function Button(props) {
  return (
    <button class='Button' data-progress={props.progress}>
      {props.children}
    </button>
  )
}
```

I've tried to note this in the docs in several locations but I feel like it's a 50/50 whether people see this. 

More detailed explanation:

It isn't the destructure itself doesn't work. It is that tracking for updates happens on property access, so if you reference them outside of a JSX binding or a "hook" (reactive primitive) no one is listening. The granular reactive approach we use doesn't re-render whole components but only the hooks and the JSX expressions so tracking only occurs in them. This is a key part of the performance and the approach we use to avoid diffing (and VDOM) but it does bring this caveat.

Hope that helps.
