### ISSUE TITLE
Solution: Solid + Goober + Shadow DOM without Custom Element

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/solid#303]
From our use case, I made a solution to use solid + goober + shadow dom without custom element. Leave there a reference and discussion base for someone with similar issue.

https://codesandbox.io/s/solid-goober-shadow-dom-without-custom-element-djr7e

**Comment by ryansolid** [comment]
Thats cool. Ive used primarily web component solutions or primarily framework so Ive yet had the need to mix something like styled components with shadow dom. Because either it would have no shadow dom or each component would just put a style tag in its JSX.  But awesome that works.
