### ISSUE TITLE
Typescript starter project?

### ISSUE THREAD

**Issue by bluenote10** [ryansolid/solid#31]
Is there any starter project showing how to use Solid with Typescript? I'm not a web developer so initial project setup is always tedious.

I was using `npm init solid app ...` but it hides the entire transpile/bundle setup behind `solid-scripts start`. What is the best way to integrate Typescript transpilation into that?

**Comment by ryansolid** [comment]
I should make a template for that. An app-ts, so that `npm init solid app-ts ....` would work. I don't have ejection currently either so there isn't a current solution for the CLI.

The CLI is still super early days. I was holding off initially to keep things simple because I'm still evaluating the build system (considering Rollup instead). But now is as good of a time as any to take the CLI to the next level.

**Comment by bluenote10** [comment]
:+1: Another nice addition would be some more transparent/minimal setups. My expectation of the starter project was to get a basic set of configs that I can adjust to my needs. The zero-config approach is nice for playing around quickly, but as soon as a config modification is needed you're lost (if not familiar with the whole JS setup shebang). I saw that you had to pull of quite some [webpack magic](https://github.com/ryansolid/solid-scripts/blob/master/config/webpack.config.js), and for a beginner it's tough to infer what is a minimal standalone setup for Solid.

**Comment by ryansolid** [comment]
Yeah that's fair. I suspected that'd to be the case for some people. I literally copied React here, like line for line and tweaked the configs. I'm conscious that it perhaps is too much. TypeScript actually adds a bunch more config in Create React App, which I removed to simplify things. The biggest benefit of this is you can upgrade the scripts as we go automatically and not worry about configuration. I think the hard part with Webpack isn't the initial config but handling all the updates and versions as things change.

React offers an eject option, that I haven't implemented that gives you the configs in your own project (so you can no longer just update react-scripts) but they are verbose like the ones you were looking at.

The minimal webpack config for Solid is just adding the babel-loader and babel-plugin-jsx-dom-expressions plugin to it. I think for someone in your position, [Parcel](https://parceljs.org/) might be the best option. It's what i use in all my Codesandbox demos. Like look at the package.json in this [Counter example](https://codesandbox.io/s/8no2n9k94l), and the .babelrc. That's all you need for modern browsers.

**Comment by codypersinger** [comment]
@ryansolid I would be willing to create a minimal TypeScript config if it would be helpful and you can provide guidance on which bundler you'd prefer used.

**Comment by ryansolid** [comment]
@codypersinger Thank you for the offer. I've been working on this, I just wasn't comfortable releasing it yet. My issue is that my TypeScript is a little weak so I'm not great at validating whether it makes sense for people. 

The CLI currently is basically a clone of create-react-app so it uses Webpack. I'm likely to look at changing that in the future as I get a better grasp of the specific requirements of users, but I took the similar tact.

So if anyone wants to give this a try and give me feedback run:
```sh
npm init solid app-ts ts-test-app
```
or 
```sh
yarn create solid app-ts ts-test-app
```
`ts-test-app` is whatever you want the directory of your project to be.

**Comment by codypersinger** [comment]
Impressively quick work. It looks more or less complete to me on the Mac side of things (not sure if you're aiming for Windows support?) - but I must confess I've never used the React CLI to generate project architecture. I'm just a TS dev who likes the look of Solid and was checking whether there were contribute-able issues. I would imagine not much is missing if you based it on React's approach / config.

**Comment by ryansolid** [comment]
I did do something different for the webpack config opting for @babel/preset-typescript to strip types instead of running tsc directly. But yeah default tsconfig.json etc are all the same.

I am hoping for Windows support. But I haven't tested that (although probably be easy given I dev on a Windows machine, although usually under WSL). 

In any case thanks for checking it out and reporting back. I appreciate the assistance. Honestly I've struggled a bit with TS so having more eyes on it as people try Solid is really helpful. I'm not ready to make the full dive myself with my projects. I hope you continue to like what you see.

**Comment by bluenote10** [comment]
Great, thanks for adding a TS template so quickly!

I'm short on time at the moment, so I only had a quick look, but on first glance it seems to work fine. The only thing I noticed is that when running the dev server the terminal prints 
```
Files successfully emitted, waiting for typecheck results...
```
without showing any results.

For the record: I also came up with a minimal TS setup, which is available [here](https://github.com/bluenote10/js-framework-experiments/tree/master/frameworks/solid-ts). I also went for the "handle typescript within babel" approach. On the one hand, simply removing the types feels a bit of a hack, because
- requires to run a separate process for actual type checking.
- requires to make sure that the babel config actually allows all TypeScript language feature 
(things like `@babel/plugin-proposal-class-properties`)
On the other hand, running `tsc` through babel is a much more complicated setup.

As far as I'm concerned the issue can be closed?

**Comment by ryansolid** [comment]
Awesome.. thanks for pointing that out about the output message. I've fixed that now. Thank you. I will consider this done for now.

**Comment by trusktr** [comment]
Where is the code for the output of `npm init solid app-ts ts-test-app` tracked? In which repo?

**Comment by ryansolid** [comment]
It's in solid-scripts: https://github.com/ryansolid/solid-scripts
Under templates.

**Comment by trusktr** [comment]
Interesting. How does `npm init solid` map to `solid-scripts`? Where's the documentation for this part of NPM?

**Comment by ryansolid** [comment]
`npm init _____` maps to `create-_____` and from there that script installs `solid-scripts`.

https://docs.npmjs.com/cli/init

**Comment by trusktr** [comment]
Ah.

<details><summary>That is confusing!</summary>

Maybe they should've defaulted to reading some folder in the same package, or something easier to intuitively discover, rather than forcing maintenance of yet another package.

</details>
