### ISSUE TITLE
Consider changing default event delegation of custom events to be opt-in instead

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#320]
The `delegateEvents(['foo']);` trick will not work with events that are not `bubbles` (or `composed` and `bubbles` if inside ShadowRoots).

**Comment by ryansolid** [comment]
Yeah I have a list of non-bubbling, non-composed events I check against. You can add your custom event to that list for the compiler(https://github.com/ryansolid/dom-expressions/blob/master/packages/babel-plugin-jsx-dom-expressions/src/config.js#L7) or use the `on` helper instead of the standard `onClick` and it adds a typical event listener(https://github.com/ryansolid/solid/blob/master/documentation/rendering.md#events).

The first option only helps with JSX but the second works in `html` (https://github.com/ryansolid/dom-expressions/blob/master/packages/lit-dom-expressions/src/index.ts#L135)

**Comment by trusktr** [comment]
> You can add your custom event to that list for the compiler(https://github.com/ryansolid/dom-expressions/blob/master/packages/babel-plugin-jsx-dom-expressions/src/config.js#L7) or use the on helper instead of the standard onClick and it adds a typical event listener(https://github.com/ryansolid/solid/blob/master/documentation/rendering.md#events).

Seems too complicated:

- nonDelegateEvents: no way to know what events to add to the list for end users. My end user may also not necessarily know about the events of elements from other authors (also my end users).
- `onclick` vs `on: {}`. One rule to many to remember. It'd be better if the syntax was based on convenience, but not on whether events work or not (they should always work)

> at the expense of ease for users not using them.


No need to sacrifice that. `onwhatever` would just always work.

What about this:

- Use the same approach you do now for native built-in events (delegating, or property set).
- For unknown events, always use `addEventListener`.
- Let the user opt out of `addEventListener` if they know the event bubbles and they want to make a performance improvement. F.e. `dlg:onfoo={}` where `dlg` makes it delegate on `document`.


Honestly I've yet to experience a case where using `addEventListener` on everything (like I currently do) has a detrimental effect on an application. It's never been a problem.

The only reason I've ever needed to use delegation was not for performance, but for making it easier to add/remove elements from a container and avoid having to add/remove event listeners each time the children are added/removed. Besides that, the compilation output will always know which elements are being added/removed, so that's technically not an issue for the compile output code, only for human-written code.

**Comment by ryansolid** [comment]
Yeah event delegation has big perf gains in list benchmarks. Like 20%. I wanted my web-component benchmarks to do well as well., And as you can imagine this started from me wanting Solid to be used with webcomponents, so I wasn't going to just opt out of performance by default there. Most of the ecosystem I made around webcomponents had this in mind and I had helpers that automatically set composed/bubble behavior.

Although admittedly I guess that's less of a concern now. Using Web Components already is sort of opting out of performance. I was hoping by being inclusive it was being more friendly but I can see why that might not be the case. The `on` helper has been my way of handling every weird named event etc that people throw at the library. But now that we have potential of namespaces maybe the other way around makes sense. Only thing to reconcile is that I don't want the standard JSX to be case sensitive.. so when people have weird camelCase event names they still need a 3rd option here which is less than ideal. I didn't even like having 2.

I think the direction you are thinking makes sense. Need to figure out how to refine the API for the different cases.

**Comment by trusktr** [comment]
Yeah, the opt-in approach will still allow the benchmark results to be as good as they can be. If the docs explain it well, it should be no problem. I believe programs that always work the way code is written is better; giving a more consistent mental model.

By the way! React 17 updated their delegation system so that instead of using `document`, it uses the render root (the one passed to `ReactDOM.render`). If you do that with Solid's `render()` that will at least get events working in ShadowDOM regardless of event `composed` values.

**Comment by ryansolid** [comment]
Hmm...changing the delegation is tricky as a runtime technique. It messes with portal event propagation, and give our approach to reactive distribution we'd need to carry it in the reactive context as we don't have top-down rendering.  I'm not saying it's impossible but a little bit trickier. Their reasoning is that it's the only way for React to act independently so they can break apart separate instances where not only is that unnecessary with Solid it actually messes with reactive system talking to other parts. 

My plan here is to change to only delegating specific events.. I copied the list that Inferno delegates since they pretty much have the same attention to performance. I'm not going to introduce a new syntax as of yet, and rely on people who really want to delegate to add to the babel config. Basically I don't think it's necessary for most things and until a need presents I'd rather not introduce more syntax. Afterall for small demos and benchmarks this will be easy enough to just add it to the list in the 2 locations (babel-preset-solid and `DelegatedEvents` Set exposed form `solid-js/web`.

**Comment by trusktr** [comment]
I'm sure there is a clean way to do it. There always is!

> Their reasoning is that it's the only way for React to act independently so they can break apart separate instances

Sadly, the fact that this fixes Web Components usage is merely a side-effect. I hope Solid can considered fully-compatible with Custom Elements, those aren't going anywhere. We have big companies starting to use Web Components for their designs systems, and incompatibility means having to choose one or the other.

> Afterall for small demos and benchmarks this will be easy enough to just add it to the list in the 2 locations (babel-preset-solid and DelegatedEvents Set exposed form solid-js/web.

Indeed that will get specific performance benchmarks working well.

The best solution will be agnostic to the infinite possible types of `CustomEvent`s that could be in the DOM, with all of their permutations of `CustomEventInit` options, _and_ not require an end user to configure it. For example, a library author using a `dlg:onbubblingcomposedevent={}` prop inside their Solid component would be confident making the choice for the end user; it would be a safe assumption that the end user doesn't need to think about.

In contrast, if the user has many custom elements in their app, they would need to be aware of the specifics of all of them to make sure they are listed in the build config, even if the app develop is not even using the elements directly (because they are inside other elements' templates). This means the end user needs to know the implementation details of all elements in the app.

**Comment by ryansolid** [comment]
For sure this isn't the suggestion of a permanent solution. I just want to be careful with syntax and I think that switching to whitelisting delegated events makes this less of a pressing issue. The default is it just works (without delegation). The event delegation mechanism still has all the code to handle composed events. I'm not cutting that.

I think it's tricky in general that events have a lot of advanced behavior that is configurable even capture vs bubble, passive etc.. custom names etc so I won't introduce new syntax until worked out everything event related to be consistent.

Is there any reason the proposed solution isn't completely Web Component friendly? Sure some custom events aren't being delegated but nothing here wouldn't work out of the box so it would never make you choose. Event delegation isn't necessary for the framework generally. The only place where not having it hurts other than performance is progressive hydration with event replay. But I think there might be some issues with that anyway that needs to be worked out with server rendered Web Components. Like Solid would need to decide how to render them. That's a whole other thing.

**Comment by trusktr** [comment]
Ah, yeah, an include list instead of a deny list.

So only delegate for known built-in events (because we know for sure they bubble and are composed), and otherwise no delegation? I believe that will work, as then Solid will use `addEventListener` for those by default.

I believe then the dom-expressions `nonDelegateEvents` would also change to `delegateEvents` for optional performance improvement when particular events bubble and are composed.

`dlg:onfoo={}` would still be neat though, but at least that could be a separate addon for another time, if ever.

**Comment by trusktr** [comment]
So the minimal change now would be delegate built-in events that are know to have `bubbles` and `composed` both `true`.

But if there are any built-in events that have `bubbles: true` but `composed: false`, then you could support those too if you change the delegation root to be the root passed into the `render()` function.

**Comment by ryansolid** [comment]
True but removes a lot of the benefit. Having delegation work beyond web component borders is where the win is. Delegating within is almost trivial when you own the shadow root (in a non-declarative way). But in any case you are correct in your understanding of the proposed solution for now.

**Comment by ryansolid** [comment]
Fixed primary issue in 0.24.0. Open to discussions in Discussions for possible new syntax.
