### ISSUE TITLE
Introduce runWithOwner

### ISSUE THREAD

**Issue by Exelord** [ryansolid/solid#323]
Hi @ryansolid!

Would you accept a PR which introduces `setContextOwner`? Im working on a feature where I need to execute some block of code in context of parent (root) owner. Without being able to change the context, Im not able to schedule eg cleanups on the root.

To give you more context why I need it, Im working on kind of global store which will lazy initialize instances. I want every instance to initialize with root context in order to schedule potential cleanups correctly.

The implementation would look like this:
```ts
function setContextOwner(owner: Owner | null) {
  Owner = owner;
}
```

As an alternative, I was also thinking about sth like `runInContext` which would revert back to previous context:
```ts
function runInContext(owner: Owner | null, callback: () => void) {
  const currentOwner = Owner
  Owner = owner
  callback();
  Owner = currentOwner;
}
```
___

For reference `getContextOwner`

https://github.com/ryansolid/solid/blob/471ae729fedbd47e5493b44c147d566183701398/packages/solid/src/reactive/signal.ts#L348-L350

**Comment by ryansolid** [comment]
I like the idea of runInContext. I was forcing separate root creation which is good in most cases but I think this lets us remove extra disposal boilerplate in some places. It does seem your case mirrors Provider a bit but I think general purpose us good. My only suggestion is the return the value returned from the callback.

**Comment by Exelord** [comment]
>  It does seem your case mirrors Provider a bit
Interesting. Could you maybe explain how it is similar to Provider? The provider indeed has its own context, but the objects it creates live outside of its owner. I would like to understand and consider if the `runInContext` would be really needed then 🤔

Sure, actually returning the result might be not that bad idea. I was just worried about exposing values that dont belong to the current owner. However this can be bypassed by using let in upper level, so there is no point in forbidding it.

I'm also considering if the `runInContext` won't be too much coupled with the `Context` concept. Maybe we should call it sth like: `runWithContextOwner` or `runInConextOwner` to not mislead Context with ContextOwner? What do you think?

**Comment by ryansolid** [comment]
Yeah I think the naming should probably be different.  We should just drop the context altogether.. And change it to `getOwner` and `runWithOwner`. Yeah I think that would be better. DOM Expressions can call it whatever it wants but Rollup will convert to our naming in the end. So let's do it. 

As for `Provider` it is just a way of injecting something in the tree so that it falls under a owner higher up the tree. See what I'm picturing here is you have some store out there. I will use a singleton as an example since it's easiest. To achieve what you want you need to wait until the owner is being created anyway to pass it into `runWithOwner`. So you might do something like:

```jsx
// entry
import { init } from "./store";

function App() {
  const o = getOwner();
  init(o);

  return /*...*/
}

// store
export let store;
export function init(owner) {
  runWithOwner(owner, () => {
    store = /* create a bunch of stuff */
  })
}; 

// some component
import { store } from "./store";

function MyComp() {
  // use the store..
}
```
With context you would do something pretty similar:
```jsx
// entry
import { StoreProvider } from "./store";

function App() {
  return <StoreProvider>/*...*/</StoreProvider>
}

// store
import { createContext, useContext } from "solid-js";

const StoreContext = createContext();
export function StoreProvider(props) {
    const store = /* create a bunch of stuff */
    return <StoreContext.Provider value={store}>{props.children}</StoreContext.Provider>
}
export function useStore() {
  return useContext(StoreContext)
}

// some component
import { useStore } from "./store";

function MyComp() {
  const store = useStore();
}
```
Hopefully that makes sense. I might be missing a scenario you are thinking of. But if you need to run under owner anyway, and need to import to bring it into the file it's kinda similar.

**Comment by Exelord** [comment]
I see. Yes, using of other owner is inevitable in my case. Thanks for explaining it on examples!

As change of the getContextOwner -> getOwner will be a breaking change for the API, I think It would be better to tackle it as separate issue.

In the meantime I created a PR with `runWithOwner()`. Let me know if it looks good to you :)

**Comment by ryansolid** [comment]
Yeah sounds good. I'm working on a breaking release right now so I can get that in then. Thanks for the PR.
