### ISSUE TITLE
[solid-styled-components] - Styled components cause children to be called multiple times

### ISSUE THREAD

**Issue by Bubz43** [ryansolid/solid#348]
**Describe the bug**
A component created with the styled function causes child components to be called twice. With multiple levels of nesting this ends up being 2 to the power of (the amount of styled parent components).

**To Reproduce**
1. Create a styled component, e.g., styled("div")``
2. Give it a child component that console.logs in the function body
3. Render the parent component
4. The console will have been logged to twice

**Expected behavior**
Each child should be called just the once.

**Reproduction**
https://playground.solidjs.com/?hash=-1865406437
Open the console and you will see that with 4 styled parents Counter has been called 16 times.

**Comment by ryansolid** [comment]
Thanks for reporting. I'm pretty sure I know what this is. The new merge helper is probably eagerly evaluating on `in` checks. Broken in 0.24.0 of Solid and later. I will get this fixed up.

**Comment by ryansolid** [comment]
Ok it's fixed in 0.24.7 and will update the playground soon. This is a pretty nasty bug that probably has been causing a lot of weirdness since the update across many library add-ons. Thank you so much for bringing this to my attention.
