### ISSUE TITLE
`TypeError: node is undefined` when updating with <$ each>

### ISSUE THREAD

**Issue by bluenote10** [ryansolid/solid#35]
I'm not sure if I'm doing something wrong here, all my attempts to use `<$ each=...>` syntax eventually result in runtime errors "node is undefined". A minimal example would be:

```js
export function Debug() {
  const [state, setState] = createState({
    data: [],
  })

  createEffect(() => {
    setTimeout(() => {
      setState({data: ["A", "B"]})
    }, 100)
  })

  /*
  // using this return works fine
  return (
    <div>
      {(state.data.map(item => <div>{item}</div>))}
    </div>
  )
  */
  // but this doesn't
  return (
    <div>
      <$ each={(state.data)}>
        { item => {
          <div>{item}</div>
        }}
      </$>
    </div>
  )
}
```

The traceback points to [this line](https://github.com/ryansolid/solid/blob/d3a1736c60233bcbae300de5e631e463dbc08205/src/dom/index.js#L48).

**Comment by ryansolid** [comment]
I do see one problem here of the bat. You aren't returning the inner template. The use of curly braces on an arrow function needs to have a return statement. In this case just don't use them:

```js
export function Debug() {
  const [state, setState] = createState({
    data: [],
  })

  createEffect(() => {
    setTimeout(() => {
      setState({data: ["A", "B"]})
    }, 100)
  })
  return (
    <div>
      <$ each={state.data}>
        { item => <div>{item}</div> }
      </$>
    </div>
  )
}
```

**Comment by bluenote10** [comment]
:+1: why didn't I see that, stupid ;)

**Comment by bluenote10** [comment]
But shouldn't returning nothing still be valid and just result in not rendering anything like in this case?

```js
  return (
    <div>
      {null}
    </div>
  )
```

**Comment by ryansolid** [comment]
Probably. I know I handle it in the normal insert case null, undefined, and booleans, but it's definitely possible each and arrays have issues. I will see if I can find any specifics.

**Comment by ryansolid** [comment]
Yeah simple and Arrays are fine. I have tests around those cases too. It is just the each as far as I can see. Thanks for reporting this I will see if I can get a fix out tonight.

**Comment by ryansolid** [comment]
I will have to think about this one more. It would be one thing to remove bad data (null, undefined) in the input array data (not that I do currently), but to have it return undefined or null when the data is legit is problematic for how I iterate and keep in sync, especially when you take fragments (multi node per item). I use the nodes themselves as markers (as I have no virtual tree). So if it isn't possible from the input data to know when you'd have no nodes I can't predict results. Editing the cached input list might be possible but I'm not sure the overhead of these checks are worth it, and again future iterations would cause wasted work.

I am thinking my best bet is make the error more obvious. Like throw an error.

**Comment by bluenote10** [comment]
> Yeah simple and Arrays are fine. I have tests around those cases too. It is just the each as far as I can see.

That Array example I gave works for you?

How would "flatmapping" work then (= mapping + filtering in one go)? It's probably a fairly common problem, e.g. you have a list of `users` and only want to render online users. Would be nice if it could be done in one operation not requiring `<$ each>` + `<$ when>` or having to filter the list first manually.

**Comment by ryansolid** [comment]
Yes the array example: https://codesandbox.io/s/solid-array-m5bt4

Hmm.. Yeah a top level conditional in an each would do that wouldn't it. I got it. I can have null/undefined create an empty TextNode. The same as returning "". That way I can keep track of them. It shouldn't have any conflict that way I believe.

**Comment by ryansolid** [comment]
I think figured it out. Babel plugin must be out of date. You are using the version from the CLI and I haven't pushed out updates in it yet. I started on the TypeScript starter and noticed. It could be causing the issue you are seeing with non-$each null inserts.
