### ISSUE TITLE
Tests in Jest aren't running properly

### ISSUE THREAD

**Issue by ryansolid** [ryansolid/solid#355]
**Describe the bug**
Solid 0.24.10 switch to using "browser" to ship client libraries and change "main" field for server breaks some client in node libraries not using bundlers. Most notably testing libraries like Jest when not compiling with a bundler.

Wrong resolution is problematic as the server side versions of Solid work differently. They don't render DOM nodes and don't have fine-grained reactivity. While the tests will compile and run they will generally fail.

There are solutions to this, using different Jest resolvers. Documenting to bring visibility.

**Expected behavior**
Test environments not fail to operate properly.

**Additional Context**
I made this change to support server setups that need access to server specific entries. Namely to support SSR in Vite. This is the expected way to handle these sort of scenarios but doesn't come without some tinkering. Conditional Exports handle this well for modern tools so this should soon hopefully be a thing of the past but for now this is the best solution.

**Comment by ryansolid** [comment]
Updated test setup.

**Comment by frenzzy** [comment]
@ryansolid could you please post a reference to see what was exactly changed re the issue? It is quite interesting topic..

**Comment by ryansolid** [comment]
What this about is having different code entries for browser and node. Most client packages ship a single code base and use the `main` field in package.json. However, when the client and server differ the unofficial standard is to use the `browser` field. Which means the main field is reserved for node.

I didn't follow this previously as Ive been using a newer feature the `exports` field. I did so because I could use as many named aliases as I liked and I used to have multiple server runtimes. However I remedied that. Older tooling and so it happens Vite doesn't work with this newer feature. So I changed to use the `browser` field. Supported in pretty much every bundler. They will look for `browser` then `module` then `main`.

Of course being unofficial, tools that run in node that have no preference on browser like Jest don't know or respect it. So I needed to add a custom resolver to do it. Basically by loading in package.json in mem and replace `pkg.main` with `pkg.browser`. Examples of that in the repo. Jest is working on `exports` field support but it might be a bit.

**Comment by frenzzy** [comment]
Thank you for the detailed explanation. I think it make sense to use the browser version by default especially because Jest uses `jsdom` as a default [test environment](https://jestjs.io/docs/en/configuration#testenvironment-string).

What do you think about testing the server version? For example to be able to catch environment-related errors like "window is not defined" early. Should solid.js users test their [universal/isomorphic components](https://github.com/ryansolid/solid/discussions/308) twice emulating browser and node, for example when they are using `import { isServer } from "solid-js/web"`?

**Comment by ryansolid** [comment]
I would have liked making browser the default and I have that with the `exports` field but unfortunately this is the way legacy is expected to work and Jest doesn't support new approach yet.

It probably best practice to test both if you have different logic in your components based on `isServer`. I'm not exactly clear how to get that setup given module resolution is different so it probably needs a completely different instance.

**Comment by ryansolid** [comment]
Ok I've released presets to work with Jest:

https://github.com/ryansolid/solid-jest

You can see them in use in solid-rx, solid-meta, solid-styled-components in this repo.
