### ISSUE TITLE
Conditional for rendering

### ISSUE THREAD

**Issue by visj** [ryansolid/solid#356]
Hey Ryan!

I've resumed my work on researching efficient rendering strategies for conditional paths. I tried to create a benchmark between Solid and Ivi looking at conditionals inside map. Below is an example code:

```js
<Show when={state.done === false}>
  <For each={array}>
    {x => {
      return <For each={array}>
        {y => {
	  if (x > y) {
	    return <div>Ok</div>
	  }
	  return null;
        }}
      </For>
    }}
  </For>
</Show>
```

How did you approach this? Basically, if you have a map -> condition -> map -> condition situation, do you render it inside out or outside in?

**Comment by ryansolid** [comment]
My For uses mapSample so callbacks are nit tracking, There are ways to get ternaries to work with fragments/createMemo but for your purposes Id use `Show` helper component.

**Comment by ryansolid** [comment]
Actually looking at your example does x/y ever change? If not what you have should be fine.

**Comment by visj** [comment]
I had some trouble setting up Solid and getting it to work. This was the example I tried to port from ivi.
```js
const t1 = Date.now();

let done = false;
let array = [1,2,3,4,5,6,7,8,9,10];
let items = ['Hello', 'Some', 'Great', 'World'];

function App() {
	if (done) {
		setTimeout(function() {
			const t2 = Date.now();

			alert('Time elapsed: ' + (t2 - t1));
		});
		return 'Done';
	} else {
		return array.map(x => {
			return x < 2 ? null : array.map((x,i) => {
				if (i > 4) {
					return div(_, _, 'Larger than 4');
				} else if (i > 4 && i < 6) {
					return null;
				} else {
					return items.map((item, i) => {
						if (i > 1) {
							return div(_, _, item);
						}
						return null;
					});
				}
			});
		});
	}
}

const root = document.getElementById('app');

render(App(), root);

array = [11,12,13,14,15,16,17,18,19,20];
items = ['Some', 'Other', 'World', 'What'];

render(App(), root);

array = [1,6,1,7,2,8,1,9,12,14,1,15];
items = ['There', 'Is', 'Still', 'Hope'];

render(App(), root);

done = true;
render(App(), root);
```

**Comment by visj** [comment]
All right, yeah, I recognized the code from S array but helpful to know which approach you went for.

I created a few new repositories. You can track my progress there. Anod is basically a merge of S and S array, where I experiment with mutation propagation for array procedures. Haven't decided if I will purse tracking or subclocks there yet.

Also experimenting in isolit, creating a merge of a virtual dom and data binding approach. The idea is to set up an entire virtual dom and then only patch it from data bindings. So then we would basically have virtual nodes all the way down, something like

EnumerableOp -> childNodes Op[] -> ProcedureOp -> EnumerableOp etc.

**Comment by ryansolid** [comment]
I see they do change.. drastically too. Nothing shared. It basically re-renders everything if this is keyed. Is the intention for this to be keyed or non-keyed? With primitives like this, it feels you want non-keyed in which case I'd use `<Index>` instead of `<For>`

**Comment by visj** [comment]
The idea was to reuse very little (you see that some nodes can be reused in the last part). It's based on the example Boris had on Ivi (but I think it was dropped from docs upon 1.0), where he tested performance of conditional rendering in maps, where ivi basically had to performance penalty of conditionals as it doesn't matter from the virtual dom perspective. So I wanted to see how big of a slowdown the data driven approach has and how to mitigate it.

**Comment by ryansolid** [comment]
I see so this is keyed by the value not by the index? Like from initial to 2nd with how `<For>` works the whole thing gets re-rendered since [11-20] has no numbers from [1-10]. Where as `<Index>` would just update the data for those 10 rows but try to keep the structure in tact. The last example basically only gets to re-use 12, 14, 15, but the internal array is completely different so ultimately no DOM nodes remain intact in any of these examples.

You also can't replicate the last part as he calls render with no data change.. There is no render in Solid of this nature. Only updating the data.. rendering on top of itself would duplicate nodes etc.. Let me see if I can recreate this for you.

**Comment by ryansolid** [comment]
Ok not promising this is super optimized but I think I recreated the logic: https://codesandbox.io/s/ivi-example-zsopf?file=/index.js. Using indexes in `<For>` actually adds a memory overhead that I optimize out when not required.

That all being said make sure you are testing the same thing. Keyed, vs non-keyed makes a big difference and I can't tell from the code if ivi is doing keyed or not.
