### ISSUE TITLE
[Tests] [Suggestion] Running the tests of some packages that use Solid

### ISSUE THREAD

**Issue by aminya** [ryansolid/solid#358]
**Describe the bug**
Coming from all the issues I have had since updating Solid to 0.24 (reported in #335), I decided to give you this suggestion:

Should Solid run the tests for some of the packages that use Solid? This will avoid this kind of breakage from happening again, and this can be used actually as unit tests for the framework itself under real conditions.

As an example, Solid-Simple-Table has 400 lines of tests testing everything like rendering, clicking, etc. This can be useful for Solid itself to test if it is functioning properly.
https://github.com/aminya/solid-simple-table/blob/master/test/SimpleTable.test.tsx
https://github.com/aminya/solid-simple-table/blob/master/demo/simple/index.tsx
https://github.com/aminya/solid-simple-table/blob/master/demo/complex/index.tsx
https://github.com/aminya/solid-simple-table/blob/master/demo/variable-rows/index.tsx

**Solution Prototype**

I already do this for one of my packages that is used by many other packages. Here is a sample script for downloading the tests of other packages and running them:
https://github.com/atom-community/eslint-config-atomic/blob/master/spec/test.js

I can make a PR adding that if you are interested. 

**Additional context**
See #335

**Comment by ryansolid** [comment]
Something like this seems useful. Right now it's pretty manual. I end up running the local repos and often copy and pasting the dist folders into a half dozen other repos each release or using pre-release tags for more complicated stuff. I think it will take some consideration in choosing the repos etc.. and probably makes even more sense when I move stuff to the new github org.

It seems prudent to setup something like this. Especially nearing 1.0. I've been concerned having to change stuff pretty rapidly when I hadn't had the chance to get into everything. But gotten my hands into most things now. Challenge has been mostly that as I widen support it has lead to fundamental changes that have been shaking things up more than I like. I wasn't expecting things to be so shaky at this point given how stable the API has been.

I don't think the right time is quite yet although I'd welcome the help getting this setup sooner than later. It's also likely I need more DOM related tests. There are some in DOM Expressions library but way fewer here.
