### ISSUE TITLE
Is there a method similar to React.createElement？

### ISSUE THREAD

**Issue by vvni** [ryansolid/solid#380]
I want to dynamically create html tags.

**Comment by vvni** [comment]
i got it.

**Comment by ryansolid** [comment]
Sure you found the answer you are looking for?

`document.createElement` is the cheeky answer but it isn't far off.

```js
import { spread } from "solid-js/web"

function create(tag, props) {
  const el = document.createElement(tag);
  spread(el, props);
  return el;
}
```
That being said doesn't benefit from compiler optimizations. Same logic present in `<Dynamic>` control flow. If you can avoid spreads do so, so if it has known attributes better to just create it imperatively.. You can always directly insert DOM nodes in Solid as:

```js
const div = <div />
console.log(div instanceof HTMLDivElement) // true
```

**Comment by vvni** [comment]
yes. <Dynamic> can satisfy！😬

**Comment by ianmobbs** [comment]
@0x219 , what was the resolution you came to when you said `i got it.`?

**Comment by 0x219** [comment]
> @0x219 , what was the resolution you came to when you said `i got it.`?

The author's answer and the Dynamic component
