### ISSUE TITLE
Error on trying to update state when DOM elements have been moved 

### ISSUE THREAD

**Issue by kfrp** [ryansolid/solid#400]
**Describe the bug**
Trying to reconcile a 'dirty' dom fails with error:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at reconcileArrays 
    at insertExpression 
    at Object.fn 
    at runComputation 
    at updateComputation 
    at runTop 
    at runUserEffects
    at batch 
    at completeUpdates 
```
I'm trying to integrate a DnD library with my Solid app, which uses native HTML5 drag-and-drop and moves DOM elements around. In my state I have arrays of ids rendered by Solid as containers and items. 

At the end of the dnd-operation, I got the old index/parent and new index/parent details from the DnD library and used setState to update my container arrays. But got the above error. Using `reconcile` also did not help.

**To Reproduce**
FYI My state (used via context) looks like this:
```
{ 
  containers: {
    pqr: ['xyz', 'abc', 'def'],
    ghx: ['jkl', 'mno'],
  },
  items: {
     xyz: { title: '...', created: '...' },
     abc: { ...etc } 
  } 
}
```
When the dnd library has moved the dom elements rendered by Solid out of sync with this state, I am not able to update the state to get back in sync. Hope I'm not talking in circles.

I have fixed my issue by putting the dragged element back to its original parent/index and then triggering the state update, which works fine but feels like it shouldn't be necessary? Did I misunderstand in thinking that this is what `reconcile` might be useful for? 

Would like to hear your thoughts.

**Comment by MrFoxPro** [comment]
Not sure I can help, but I have to say that if you are using framework that provides connection between state and dom, it is assumed that your elements are in sync with state. I think the only right way to do this is to implement dnd logic with declarative way. As it was in React and other frameworks.

**Comment by MrFoxPro** [comment]
By the way, could you please provide reproducable example e.g. on codesandbox?

**Comment by ryansolid** [comment]
> I have fixed my issue by putting the dragged element back to its original parent/index and then triggering the state update, which works fine but feels like it shouldn't be necessary?

This is how drag and drop works in every modern framework to my knowledge. Only thing that sucks is it means the HTML elements are recreated if the target is a different list/zone. Not sure that is easily rectified without doing some sort of hacky stuff like managing the nodes directly. While the library expects the state drive things. Technically `<For>` returns a `createMemo` of an array of DOM nodes. So as long as that memo reflects new DOM nodes it works. Like you could insert a signal that is an array of DOM nodes, and literally move DOM nodes around by updating that signal. But it wouldn't be as data-driven.

On aside `reconcile` has nothing to do with the DOM and is just a deep diff of state data.

**Comment by kfrp** [comment]
Fair enough. So my lesson is that in order to update state correctly (and without errors), the current state needs to be in sync with the UI. I thought maybe `reconcile` forced the dom update even if the current state was out of sync with the dom.

What you say clarifies things and gives me some confidence that there isn't an obvious/cleaner way to update state _from_ the dom without first reverting the dom. Thank you for your input.
