### ISSUE TITLE
Effect cannot watch change of array length

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/solid#413]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**

If I have an array in a state, when I push item into it, the effect of wath/use of the `array.length` will not rerun.

**To Reproduce**

https://playground.solidjs.com/#NobwRAlgJmBcYA4A2A2AhgZwwdwOYoCYAGAWwyQBYB7ADwBcKBWARxLABowA7NEgUzhgSaCFw5g6ATwAOA+HQw1xGKgFcATgGM5kEtKrq6AAhBH1fLlD7qjAXyMAzdVRJGA5CqTQAtACsMAPTYfABGbgDcADpcEHoGxqaa5mh0fADKdCl87EYAYgY50s5QqtpG7El8WQCiDg58mnT2Ti7unj7+EdHRDqpcjRBUXEYAMhAYCgAUAJQm0UZGmkMTRsATWTkYfHQZWQC6RgC8i8mpu6mTIF4TGLCrwHt7ttPzRq9bdAAqsXxqdJMzI4APjmwwWRg+5z4kzc1wUbkKxVKfAAPGguJIgZM4RhgaDweCccAiHsAHTSVQYAAWkwILzBC2e9MZOQAjEQOfTXksuCsHBB1BMxitDutUqSiSS3lxXuY6BphiioBAAG5A14LJWqoEAQUaqjQSEWai4dDuIDFfAl4wUxLJSAsuDoVNsKICyrVGqMWrVevlhuNfTNJn5growroEsdztd7u1XpREaMcMOFsy4slTyMAXVDO9SZTIFDQpt9hzCfyNiqmipqct1putlzBIWIC9BLheMTNuTNtTcLLzZbtgTAUrudebo9uZHMq4vX6dEGwwjkyKVGkGFmbbBcoV3unSyD5vXm4bkYdXCdLqn8a4s+i5ks1gBs0OIO7N2zQJyUComlUfhTVJXBtmqB0gLoAAhSQAEkoBhNBpGkNxpnpMBbD2IA

**Expected behavior**

all counts change from 0 to 1, but only demo 1 and  demo 3 works

**Additional context**

If this does not work, How can I watch the change when item was insert or removed from the array?

**Comment by ryansolid** [comment]
Hmm... Good find. This is tricky. I know to notify on change by comparing to the old value, but length updates before the proxy trap is hit. So it doesn't notify. I need to trigger length on the property change. I will look into it.
