### ISSUE TITLE
The published package for `react-solid-state` contains uncompiled typescript

### ISSUE THREAD

**Issue by thefliik** [ryansolid/solid#414]
**Describe the bug**

The [`package.json`](https://www.runpkg.com/?react-solid-state@0.26.1/package.json) for the `react-solid-state` package defines the module entry point as `"module": "src/index.js"` however that same published package does not contain a `src/index.js` file. Instead it contains a [`src/index.ts` file](https://www.runpkg.com/?react-solid-state@0.26.1/src/index.ts). This appears to be a bundling error. Additionally, if you don't have an `index.d.ts` file at the top level of a package I think (?) you need to define a `typings` entry in the `package.json` that points to a type definion entry point (I could be mistaken about that tho).

**Comment by ryansolid** [comment]
Thanks for bringing this to my attention. I probably should have looked closer at the PR that added TS support here. That library was was all JS and it was converted to TS by the generosity of a community member. I will review the build process and publishing.
