### ISSUE TITLE
solid 0.26 breaks the buttons and breaks tracking of the props in `createComputed`

### ISSUE THREAD

**Issue by aminya** [ryansolid/solid#417]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**
0.26 breaks two things in [solid-simple-table](https://github.com/aminya/solid-simple-table), which I don't know how to fix
- it has broken the sort functionality. The buttons had onclick callbacks that used to sort 

<details>
<summary>image</summary>

Now:
![solid](https://user-images.githubusercontent.com/16418197/115598748-5e919b80-a2a0-11eb-8774-05634cbf811d.gif)

Previously:
![Simple table demo](https://github.com/aminya/solid-simple-table/raw/master/other/simple-table-demo.gif)

</details>

- it has broken updating the rows whenever `props.rows` changes. [I was using `createComputed`](https://github.com/aminya/solid-simple-table/blob/14c1939966d6f50fb73cffdc43a005fc48120b6c/src/SimpleTable.tsx#L20) which used to call `setRows` to update the  `rows.props`. But this doesn't seem to work anymore.
```ts
  // update the local copy whenever the parent updates
  createComputed(() => {
    setRows(props.rows)
  })
```

<details>
<summary>image</summary>

Now:
The rows aren't updated

Previously:
![variable](https://user-images.githubusercontent.com/16418197/115599743-8d5c4180-a2a1-11eb-89db-7f0b3f7288ab.gif)

</details>

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Install [solid-simple-table](https://github.com/aminya/solid-simple-table/pull/9) from this branch
2. Run `npm run demo.simple` or `npm run demo.variable-rows`
3. Click on the sort buttons

**Expected behavior**
- Clicking on the button should sort the row
- New rows should be added if `props.rows` changes

**Reproduction**
If applicable, add a link to a simple reproduction on a site like https://codesandbox.io or https://playground.solidjs.com.

**Additional context**

**Comment by ryansolid** [comment]
I'd need to see how the parent is updating it, but I suspect there is a mutation on the same array setting the same array over and over and now it isn't re-triggering. As a sanity test, pass `false` as the second argument to the `createSignal` where you create your row signal. But more than likely this time we have to have to trace back to where the set is coming.

**Comment by aminya** [comment]
> I'd need to see how the parent is updating it, but I suspect there is a mutation on the same array setting the same array over and over and now it isn't re-triggering. As a sanity test, pass `false` as the second argument to the `createSignal` where you create your row signal. But more than likely this time we have to have to trace back to where the set is coming.

Oh, thanks. Passing `false` to `createSignal` fix the button issue. Now sorting works. 

However, still `createComputed` doesn't reflect the `props.row` changes.

**Comment by ryansolid** [comment]
The `createComputed` itself is only going to respond when prop.row changes which suggests that the problem is in the parent. The change with 0.26 is that signals only notify on change now by default and by change I mean reference equality. So look at how you are updating the rows in the parent.

**Comment by aminya** [comment]
It is just updating the `props.rows` object directly before passing it to `SimpleTable` component. Also, in one of the tests I do this:
https://github.com/aminya/solid-simple-table/blob/14c1939966d6f50fb73cffdc43a005fc48120b6c/demo/variable-rows/index.tsx#L16

**Comment by ryansolid** [comment]
This example pushes and sets, so the signal second argument also needs to be set to false because you aren't doing an immutable set.

https://github.com/aminya/solid-simple-table/blob/14c1939966d6f50fb73cffdc43a005fc48120b6c/demo/variable-rows/index.tsx#L17

**Comment by aminya** [comment]
That does the job! [Now all tests pass](https://github.com/aminya/solid-simple-table/pull/9).

At first, when I read the changelog I didn't fully understand what "Signals no longer always notify by default" means. Maybe adding an example to the changelog and writing a short migration guide can prevent potential confusion for other users.

**Comment by ryansolid** [comment]
To be fair I think I'm going to consolidate this API one more time for 1.0. I wanted to get the behavior out quickly without forcing everyone to change things all over the place. I wanted to make the migration easy for most cases but I think I should normalize the arguments to the primitives. So I apologize that this will change one more time for 1.0. But then we will be done.
