### ISSUE TITLE
potential bug: cannot run tests

### ISSUE THREAD

**Issue by thefliik** [ryansolid/solid#418]
Attempting to clone and run this repo's tests locally fails because [this file](https://github.com/ryansolid/solid/blob/main/packages/solid/src/index.ts#L38) cannot be found. My guess is that you have that file defined locally, but it is untracked in git?

More broadly, it would be helpful if a [`.devcontainer.json` file](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) was added for this repo to make getting up and running easier, but I notice that you've used npm v7 which doesn't have a ready made `.devcontainer.json` config template available. Is npm v7 important or incidental?

**Comment by ryansolid** [comment]
Run build before you run tests. Solid builds itself from my library DOM Expressions. Because TS doesn't let you bundle type declarations I manually copy the type files as part of the build process.

Run `npm run build` and you should be able to run the tests after.

**Comment by thefliik** [comment]
Gotcha. I've run into some build errors, but that could be the result of my using npm v6. Regardless, I'll figure it out.

**Comment by ryansolid** [comment]
I've heard there are issues with npm 7.. but I've been using 6.

**Comment by thefliik** [comment]
Interesting, [the lockfile](https://raw.githubusercontent.com/ryansolid/solid/main/package-lock.json) in this repo is listed as `"lockfileVersion": 2`, which I believe is specific to npm v7.

It looks like this shouldn't matter though, as lockfile v2 is considered backwards compatible with older npm clients according to [this npm blog post](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major).

**Comment by ryansolid** [comment]
Yeah you're right I do appear to be on 7.
