### ISSUE TITLE
Is posible to use mobx state tree with solidjs?

### ISSUE THREAD

**Issue by Relaxe111** [ryansolid/solid#57]
Hello this is a question. 
Can I use a mobx state tree with solidjs?

**Comment by ryansolid** [comment]
Yeah, it should be possible. But only as the store technology. The local state would have to use Solid's primitives. It's just a matter of wiring up the change mechanism. I will say this. Using snapshots is a bit counterintuitive. You can use Solid's `reconcile` method. But what you are doing is taking fine-grained change. Changing it to immutable snapshot, then having Solid diff it back to a fine-grained change to update the view. Something like MST's `onPatch` might work better. But I'm not completely familiar with their API.

But if you are really invested in MobX almost sounds like you might be better served looking at my other project: [mobx-jsx](https://github.com/ryansolid/mobx-jsx)

**Comment by seannowotny** [comment]
If anyone gets mobx or mst to work with solidjs please let us know.
