### ISSUE TITLE
Why does it return the value if the prop name is "symbol"?

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#6]
https://github.com/ryansolid/solid/blob/de578778fbc6333981c0a67c366314ec3c4ce667/src/State.js#L84

Just curious what that does.

**Comment by ryansolid** [comment]
Basically these are things that don't get mapped or tracked. An object might have a iterator symbol etc and we just pass it back unmodified. I haven't hit a scenario where it made sense to map/track a symbol so it's an early exit. If you can think of any I'd be interested.

**Comment by ryansolid** [comment]
I realized this was too specific of an optimization and removed from 0.2.0.
