### ISSUE TITLE
Typings for setState

### ISSUE THREAD

**Issue by high1** [ryansolid/solid#62]
Hello,
I was just going through the examples, and ran Counter sample with Typescript and a minimal setup - parcel, babel-preset-solid and got an error here:
`setState('counter', c => c + 1);`  -> c implicitly has any type
if casted to number
`setState('counter', (c: number) => c + 1);` -> Type 'undefined' is not assignable to type 'number'.  which comes from the definition of the StateAtom
so, i had to do this
`setState('counter', (c: unknown) => (c as number) + 1);` which is kinda awkward. Am I missing something or the definitions could be improved here?

**Comment by atfzl** [comment]
Hi @high1,

The way of setState you are using would be difficult to make typesafe.
I suggest you use this alternate syntax:

```js
setState(state => ({ counter: state.counter + 1 }));
```

This is compatible with typescript.

**Comment by ryansolid** [comment]
Hmm.. I was hoping TypeScript would work here. Admittedly I built the API's without TypeScript in mind and then I had to do work to make them fit. The path syntax is useful for deep setting, and I find I use that form (`setState('counter', c => c + 1)`) a lot over the object form.

To tell you the truth I thought that types would match properly in this case. I'm in no means a TypeScript master but I was hoping that would be expandable to cover the common cases atleast up to a depth of 8 or so. I can try to look into it, but this is also a place where I could use some help from TypeScript aficionados. I do really wish to make this TypeScript compatible it just seems that there are weird gotchas around every corner.

**Comment by high1** [comment]
> Hi @high1,
> 
> The way of setState you are using would be difficult to make typesafe.
> I suggest you use this alternate syntax:
> 
> ```js
> setState(state => ({ counter: state.counter + 1 }));
> ```
> 
> This is compatible with typescript.

I wanted to check out all the possibilities.



> Hmm.. I was hoping TypeScript would work here. Admittedly I built the API's without TypeScript in mind and then I had to do work to make them fit. The path syntax is useful for deep setting, and I find I use that form (`setState('counter', c => c + 1)`) a lot over the object form.
> 
> To tell you the truth I thought that types would match properly in this case. I'm in no means a TypeScript master but I was hoping that would be expandable to cover the common cases atleast up to a depth of 8 or so. I can try to look into it, but this is also a place where I could use some help from TypeScript aficionados. I do really wish to make this TypeScript compatible it just seems that there are weird gotchas around every corner.

I'm not that prominent with TypeScript, but I think that you could replace any in StatePath defintion with unknown - this way only the first type needs to be declared,
`setState('counter', (c: number) => c + 1);`

**Comment by high1** [comment]
I'll see if I can work something out with this - hopefully, just replacing any with unknown in state definitions will do.

**Comment by bluenote10** [comment]
The state updates of the form `setState(<string>, ...)` are inherently non-type safe, because the `<string>` content obviously cannot be evaluated at compile time*. I guess working with `unknown` is the only option, which is a pity.

I'm only using the type safe versions of `setState` mentioned by @atfzl. The only situation where I have to fall back to the non-safe versions is for nested updates. The API is a bit inconsistent in that regard, but I'll discuss that in a separate issue and leave the scope of this issue for string based updates.

[*] The Solid readme mentions this API early on. One of the reasons why I first discarded Solid was because this API immediately looked troublesome to me. I only later found out that the other ways to use `setState` are actually type safe. In my opinion it would give a better impression to mention the entire `setState` API less prominently, there are much nicer things in Solid ;).

**Comment by atfzl** [comment]
@bluenote10 for react/redux application i use [immer](https://github.com/immerjs/immer) for nested updates. But immer also uses proxy like solid-js, so they might be interfering. I tried immer with solid and it doesn't work for nested updates.

**Comment by atfzl** [comment]
@ryansolid it would be cool to have an interface like immer if possible where we can just mutate the state in the setState function.

Maybe it is possible as we are already using proxy with the state object, immer also uses proxy for creating the new state without mutating the original one.

OR 

If we can make the state compatible with immer to allow creating a proxy by immer over an already proxy with was made by solid.

**Comment by ryansolid** [comment]
Is ImmutableJS (setIn) type safe? That's the sort of API was going for. I'm not going to lie. Sort of started down this way to avoid Immer like API. I really disliked writing everything mutable. It was one the first things I decided when not being like MobX either. I mean immer approach is unnecessary here. It's a mutable API over a mostly immutable system. Solid is already mutable under the hood and I'm forcing this API intentionally. I really like the terseness. As you can tell by its prevalence in the Readme how important I feel this development is for fine grained reactive systems.  Of course I expose primitives so other Proxy solutions are possible but they aren't currently something I'm interested in core.

I worked hard to figure out the exact API approach that made sense to create the experience I was going for. I has no idea it wasnt going to type safeable. Coming from my perspective, I'm starting to feel like the team that started using the alpha product before it's ready. If this was the first or the second time that's one thing. Given TypeScript prevalence I've been hoping Im just missing something.

So before I say something nasty about TypeScript, I will stop. And just thank you all for helping me with this. I just don't know. I've used plenty of typed languages. There is just something about TypeScript.

**Comment by high1** [comment]
> 
> 
> Is ImmutableJS (setIn) type safe? That's the sort of API was going for. I'm not going to lie. Sort of started down this way to avoid Immer like API. I really disliked writing everything mutable. It was one the first things I decided when not being like MobX either. I mean immer approach is unnecessary here. It's a mutable API over a mostly immutable system. Solid is already mutable under the hood and I'm forcing this API intentionally. I really like the terseness. As you can tell by its prevalence in the Readme how important I feel this development is for fine grained reactive systems. Of course I expose primitives so other Proxy solutions are possible but they aren't currently something I'm interested in core.
> 
> I worked hard to figure out the exact API approach that made sense to create the experience I was going for. I has no idea it wasnt going to type safeable. Coming from my perspective, I'm starting to feel like the team that started using the alpha product before it's ready. If this was the first or the second time that's one thing. Given TypeScript prevalence I've been hoping Im just missing something.
> 
> So before I say something nasty about TypeScript, I will stop. And just thank you all for helping me with this. I just don't know. I've used plenty of typed languages. There is just something about TypeScript.

Well. I must say I'm stumped. When you use createState on the live repo, setState('counter', (c: number) => c + 1); works just fine. It's seems that when types are exported, this stops working. Anyway, I think that if  StatePath uses NestedStateSetter<unknown> instead of NestedStateSetter<any>, this would work.

**Comment by atfzl** [comment]
@ryansolid the current `setState('counter', (c: number) => c + 1);` api does not work for nested updates, so currently we can only use `setState(state => );` like method for nested updates.

What i am suggesting is to keep the same model i.e. React like unidirectional flow without mutating state like mobx, but allow mutating the state only inside the setState method and not outside of it. So it would be mutating only in a controlled environment.

**Comment by ryansolid** [comment]
I'm super confused. What do you mean it doesn't work? https://codesandbox.io/s/8no2n9k94l works.

Can you give me an example? I think there is some confusion over what the API actually is.

**Comment by atfzl** [comment]
@ryansolid I was taking about deep nested updates. I had confusion over the api if it had support for nested updates, but just saw your [comment](https://github.com/ryansolid/solid/issues/68#issuecomment-529073342). I haven't worked with immutablejs from where this api is inspired. Maybe we should add examples in docs showing deep nested updates ?

**Comment by ryansolid** [comment]
Yeah, I was thinking that the `setState('counter', c => c + 1)` was one. But I guess people all assume that is single depth when it's arbitrary depth. The state part of the docs all gives a lot examples of using filters and wildcards.

https://github.com/ryansolid/solid/blob/master/documentation/state.md

**Comment by high1** [comment]
StatePathParth is probably missing number as option. It's defined as ```declare type StatePathPart = string | (string | number)[] | StatePathRange | ((item: any, index: number) => boolean);```
so ```setState('list', 2, 'read', true); ```shows error on 2
```declare type StatePathPart = string | number | (string | number)[] | StatePathRange | ((item: any, index: number) => boolean);```
Btw, the PR worked - ```setState('counter', (c: number) => c + 1)``` shows no warnings from TS.

**Comment by ryansolid** [comment]
Yeah that is an omission. I will update that tonight.

**Comment by ryansolid** [comment]
Ok committed it up. It will be in the next npm release in the next couple of days. If nothing else, I think we can close this one? I think the more progressive discussion will carry on in #68 .

**Comment by high1** [comment]
Yes, everything is solved.
