### ISSUE TITLE
Workaround for /* prettier-ignore */

### ISSUE THREAD

**Issue by atfzl** [ryansolid/solid#64]
This is not an issue, just a suggestion.

Instead of telling prettier to ignore code, change the statement:
```js
{(state.counter)}
```
to
```js
{(void 0, state.counter)}
```

This is compatible with prettier and even with typescript.

**Comment by ryansolid** [comment]
Hmm.. thanks for suggestion. I can see it working on a small view alright. I find where I use Prettier I end up doing one large ignore at the top of the JSX to handle the whole view.

**Comment by atfzl** [comment]
Yeah, it is a little ugly to be used in a big component.
Just wanted others to be aware of an alternate variant.
