### ISSUE TITLE
TypeScript and TSX support?

### ISSUE THREAD

**Issue by MikaelPorttila** [ryansolid/solid#72]
**Question:**
Will or does Solid support .ts and .tsx files?

Thanks!
/ Micke

**Comment by ryansolid** [comment]
Yes. Solid supports TypeScript. We are still improving the type definitions. You can try it by using Create Solid App. With npm 6 or later you can run:
```sh
npm init solid app-ts example-app
```
to create and install a Solid TypeScript project base.
