### ISSUE TITLE
<Show /> throws an error with typescript

### ISSUE THREAD

**Issue by Harshit369** [ryansolid/solid#74]
Show component doesn't appear to work well with typescript@3.5.3. Its types are defined to return children | undefined based on `when` condition like:
```ts
export declare function Show<T>(props: {
  when: boolean;
  fallback?: T;
  transform?: (mapped: () => T | undefined, source: () => boolean) => () => T | undefined;
  children: T;
}): () => T | undefined;
```
but when its used as a JSX element inside a warpper 
```jsx
<div className={wrapperStyles}>
 <Show when={(state.showButton)}>
  <button className={buttonStyles}>Add item</button>
 </Show>
</div>
```
it appears to throw this error trace at `<Show>`.
```
JSX element type '() => string | number | Element | ArrayElement | FunctionElement | MatchElement | undefined' is not a constructor function for JSX elements.
  Type '() => string | number | Element | ArrayElement | FunctionElement | MatchElement | undefined' is not assignable to type 'FunctionElement'.
    Type 'string | number | Element | ArrayElement | FunctionElement | MatchElement | undefined' is not assignable to type 'Element'.
      Type 'undefined' is not assignable to type 'Element'.
``` 
Am I doing something wrong here? though typings look fine to me, I'm unable to make it work.

**Comment by atfzl** [comment]
@Harshit369 use the latest version of `babel-plugin-jsx-dom-expressions`.

**Comment by ryansolid** [comment]
Yeah, the type error looks like it is from a version of `babel-plugin-jsx-dom-expressions` before 0.11.3 where I fixed the definition of JSX Element. See if updating helps. Did you install from create-solid? I'm wondering if this is just bad package locks somewhere. Maybe with `babel-preset-solid`?

**Comment by Harshit369** [comment]
@ryansolid No, I rolled my own with custom webpack config. I seem to be running an old version of `solid-js` having `babel-plugin-jsx-dom-expressions@~0.11.2`. Updating both to latest fixed it. ✅

**Comment by ryansolid** [comment]
Great. Getting the right types for the JSX has been a bit of struggle since Solid compiles it very differently than a Virtual DOM. So it's been a bit of a work in progress even up to recently. It is in a better place now, but I'm sure there are still some issues. If you find any more, don't hesitate to submit another issue.
