### ISSUE TITLE
getting `node.current is not a function` after 0.10.6 and later

### ISSUE THREAD

**Issue by atfzl** [ryansolid/solid#76]
I am getting `node.current is not a function` when i use filter or map in an expression: https://codesandbox.io/s/solid-simple-todos-c04cf 

but reduce is working:
https://codesandbox.io/s/solid-simple-todos-gtbb5

I also tried the [solid-todomvc](https://github.com/ryansolid/solid-todomvc) with solid-js 0.10.7, it is also giving the same error.

**Comment by atfzl** [comment]
Seems like the issue is because of https://github.com/ryansolid/solid/commit/a35c622303f682f06da56d4de99b73e3713947ea

Reverting the change fixed it.

**Comment by ryansolid** [comment]
Ok, I should have added tests and was too hasty with that change. There are cases where we want to track functions in state.  Array native methods being the obvious place where its unnecessary. I figured with the change to limit plain objects removed most other cases. I will try to track why. I suspect it has to do with Arrays specific notifying behaviour. Maybe simplest is only track functions on objects.

**Comment by ryansolid** [comment]
Turns out it's the constructor property causing it now since it gets past the function check. I still think tracking Array native methods are a waste though so. I'm doing a `hasOwnProperty` check on functions to ensure only intentionally included functions are being included.

Fixed in 0.10.8.

**Comment by atfzl** [comment]
Thank you 👍 

But why are you tracking functions 🤔

**Comment by ryansolid** [comment]
See https://github.com/ryansolid/solid/issues/73.

It's not perfect in the sense nested setters have to be objects or double nested functions. Truthfully not sure all the cases, but didn't have a great reason not to either.
