### ISSUE TITLE
Allow parent to pass forwardRef callback to component as a prop

### ISSUE THREAD

**Issue by Harshit369** [ryansolid/solid#77]
In an app with shared components architecture like mine, I'm finding it difficult to let the user decide the callback for `forwardRef`. let's say we have a common `<button></button>` component which is being used across the whole app. I want to add some event handlers to the element the best way would be to use `forwardRef` which provides the instance of the actual DOM node.

child Button component
```
(props) => <button {(...props)}>{(props.children)}</button>
```

inside parent component
```
 <Button className="specialButton" forwardRef={(el) => el.doSomethingWithIt() }>{(state.buttonText)}</button>
```

This doesn't stick with the underlying <button> element as `forwardRef` is passed as `ref` prop to the child. so, spreading `{...props}` assigns `forwardRef` function as a `ref={functionExpectingElementReference}` to it. which doesn't and shouldn't work according to the docs.

and if I try to be smart and assign forwarded `ref` from the parent to child as `forwardRef` myself. it throws typescript type-checker error. 

----

As of now, I'm using it with a workAround like this

button Component
```
({initializeRef, ...rest}) =>  <button forwardRef={initializeRef} {(...rest)}>{(props.children)}</button>
```

inside parent component
```
 <Button className="specialButton" initializeRef={(el) => el.doSomethingWithIt() }>{(state.buttonText)}</button>
```

Is it like, I'm using it the wrong way or exposing too much to the user? or can we do something to make its usage a bit simpler?

**Comment by ryansolid** [comment]
Yeah I noticed this when I was doing fixes for the 0.10.7 release (fixes for https://github.com/ryansolid/solid/issues/75). I let spreads handle both ref/forwardRef as functions when applied to DOM elements. So your example should just work (passing in forwardRef and spreading over ref), but I'm guessing TypeScript gets in the way as usual.

The current behaviour probably can be improved.  It is as follows:
1. Element
    a. `ref={someVar}` compiles to `someVar = element`
    b. `forwardRef={fn}` compiles to `fn(element)`
    c.  Spread treats ref and forwardRef both as functions and executes `fn(element)` for both.
2. Component
    a. `ref={someVar}` compiles to `props.ref = (element) => someVar = element`
    b. `forwardRef={fn}` compiles to `props.ref = fn`
    c.  Spread passes exact fields through perhaps wrapping in a getter if spread is dynamic.

I did the renaming initially to make the internal api consistent so regardless  of whether the consumer used ref or forwardRef you can build your components knowing that a `props.ref` is what you are dealing with. I missed spreads in that initial consideration though. With 0.10.7 I added support for spreading props.ref as a function, so maybe a TypeScript gap, but should work. Spreading over Components though is broken as a straight passthrough will work when spreading over the DOM (as it handles both `ref` and `forwardRef`) but it won't be on the expected property.

So I have some options here:
1. Leave mostly the same and fix Component Spread and possibly types on DOM spread of ref.
2. Always use functions for ref the way `forwardRef` works, and lose the ability to do simple refs.
3. Have forwardRef not forward to ref and have the Component builder communicate what they are looking for (Not really an option).

I'm still leaning towards 1, as it keeps the API the most open, but 2 is not unreasonable. Do any other options come to mind?

**Comment by ryansolid** [comment]
I need some help with my TypeScript here. I added a test for this in `test:types` [here](https://github.com/ryansolid/solid/blob/aae2befe460b1211a60337b2a8ea837887248c40/test/types/dom.tsx#L108).  But I'm not sure if I'm working just too hard to coerce it. It works in the latest versions. Maybe someone who understands how TypeScript with JSX works better can comment on how I should handle this?

**Comment by Harshit369** [comment]
> Leave mostly the same and fix Component Spread and possibly types on DOM spread of ref.

Sounds good for now and will do the job I think. 
But I think this might introduce a few additional checks and edges for you to handle and may bite in the future. 

> Always use functions for ref the way forwardRef works and lose the ability to do simple refs.

making ref a function seems a peaceful option too. this will end the confusion for the user to what to expect inside the component or what will serve the purpose. though it will introduce some λ function just to store the reference but I think it's for everyone's good.

**Comment by Harshit369** [comment]
```tsx
Component = (props: (JSX.HTMLAttributes<HTMLDivElement> & {ref?: (e: HTMLElement) => void})) => <div {...props} />,
```
You will have to use this merge props everywhere you'll be doing this kinda stuff to pass forwardRef callback as ref. 

A bit improvement to this would be to give somthing:
```tsx
type propType = JSX.HTMLAttributes<HTMLDivElement>
Component = (props: ( propType & {ref?: propType['forwardRef']})) => <div {...props} />,
```

**Comment by Harshit369** [comment]
Also how about if we could do something like conditional types for `CustomAttributes` types
```ts
interface CustomAttributes<T> {
      ref?: T extends HTMLElement ? T : (el: T) => void;
      forwardRef?: (el: T) => void;
      classList?: { [k: string]: boolean | undefined };
      events?: { [key: string]: EventHandler<T, CustomEvent> };
}
```

**Comment by ryansolid** [comment]
Ok, yeah if that works that looks great. That is the sort of stuff I was looking for. My TypeScript knowledge is still very basic. I was fiddling with it for an hour just to get what I had working. Super stoked on making that will work smoothly.

**Comment by ryansolid** [comment]
Yeah looks good. Applied the type update in Babel Plugin JSX DOM Expressions 0.11.5. Helped me simplify the test without assigning the custom property. Thanks for your help. I will consider this closed for now.
