### ISSUE TITLE
What the "sample" proxy trap helper for?

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#8]
https://github.com/ryansolid/solid/blob/de578778fbc6333981c0a67c366314ec3c4ce667/src/State.js#L82

**Comment by ryansolid** [comment]
This returns the sample function which is used very much like peek in knockout or sample in S.js. It pulls out the value without causing change detection to track. The returned value is still proxy wrapped  but accessing that property in the first place won't get registered by the parent computational context.

**Comment by ryansolid** [comment]
Deprecated in 0.2.0 since always returning proxies no need for this anymore.
