### ISSUE TITLE
Unable to get JSX expressions working in Webpack setup (compiles to React.createElement)

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#84]
I'm trying to get JSX DOM expressions to work in my Webpack setup. The setup needs to handle both JSX for files using React (existing code base, files with `.tsx` extensions) and JSX for solid files (files with `.solid.tsx` extensions).

I made a reproduction of the problem, and when you run it you'll see an error like `React is not defined` because the expressions are compiled to `React.createElement()` calls.

**Comment by trusktr** [comment]
Reproduction: https://github.com/trusktr/solid.js-react-typescript

```sh
git clone git@github.com:trusktr/solid.js-react-typescript.git
cd solid.js-react-typescript
git checkout solid-issue-84
npm install
npm run build:dev
npm run browser # opens a browser tab
```

then see the error in the console.

**Comment by trusktr** [comment]
@ryansolid Oops, ironically, I didn't copy the correct webpack config, which yielded the same error as I have in my other repo... but now that I updated it, the above minimal reproduction actually works! 

I gotta find out what's different in the private repo.

**Comment by ryansolid** [comment]
Ok well, I guess that is one step forward. Good luck! Let me know if I can help.

**Comment by trusktr** [comment]
Sorry for the noise! It can sometimes be tricky to tell if issues are on one side or the other.
