### ISSUE TITLE
[TS] breaking change in 0.11: ShadowRoot object is no longer assignable to second parameter of render() function

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#87]
The [web component example](https://github.com/ryansolid/solid/blob/master/documentation/components.md#web-components) now fails in TypeScript in 0.11:

```js
    !this.shadowRoot && this.attachShadow({mode: 'open'});
    this.dispose = render(this.render.bind(this), this.shadowRoot!); // ERROR
```

The error is:

```
Argument of type 'ShadowRoot' is not assignable to parameter of type 'HTMLElement'.
  Type 'ShadowRoot' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 177 more.
```

In version 0.10, the type of the second parameter was `Node`, which a shadowRoot is assignable to.

**Comment by ryansolid** [comment]
Nice find.. thanks I actually had to fix this for the Preact version of my Web Component library. I will get this fixed up tonight.

**Comment by trusktr** [comment]
Just curious, is this released yet? Ran `npm install solid-js` last night on a new project and got the same error.

**Comment by trusktr** [comment]
I see what `MountableElement` is trying to do. `Node` is not in that list, because it can't be mounted. It is more of an abstract base class.

Current `MountableElement` is `Element | Document | ShadowRoot | DocumentFragment`, but maybe that needs to be updated actually. `Element` is an abstract base class too. Maybe it should be `HTMLDivElement | HTMLInputElement | ... | SVGSVGElement | ... | Document | ShadowRoot | DocumentFragment` to captute only the actually-mountable elements.

**Comment by ryansolid** [comment]
Yeah I debated this. I just copied Preacts types here. I do think more general is probably better, but mostly since I don't care about type specificity that much. Although I'm not sure how much this would be hit. I have no issue adding this to the types when I'm in there next.

**Comment by trusktr** [comment]
Made a PR: https://github.com/ryansolid/solid/pull/124
