### ISSUE TITLE
createEffect works, but attribute expression reactivity with same variable is not being triggered

### ISSUE THREAD

**Issue by trusktr** [ryansolid/solid#90]
Seems like I'm experiencing the same issue described in https://github.com/adamhaile/surplus/issues/27, but with Solid.

I have an expression like this:

```jsx
<line strokeWidth={(console.log('re-run strokeWidth attribute'), this.width)} />
```

But the `console.log` only fires once, initially, and isn't updating on changes to the underlying reactive variable.

- `this.width` is a getter that calls `this.ratio`.
- `this.ratio` is a getter that calls `this.animationAmount`.
- and finally, `this.animationAmount` is a getter that reads from a reactive signal made with `createSignal`.

Seems like the problem is only in the attribute. Because if I run something like

```js
    createEffect(() => {
      console.log('anim: ', this.width)
    })
```

then I see the logs during my animation. It is only the attribute that isn't being updated.

**Comment by trusktr** [comment]
Oh wait! I think I know... the `strokeWidth` is being passed as a property, but maybe that doesn't work on SVG elements. Let me see...

**Comment by ryansolid** [comment]
Right now SVG isn't doing any camelCase mapping. Which you have noted in both your issues. Essentially they always set as attributes so I thought of just using all the attribute names. I can look at mapping the camelCase back to attribute names I just hadn't really considered it.

**Comment by trusktr** [comment]
Yes indeed. So I changed it to

```jsx
<line stroke-width={(console.log('re-run strokeWidth attribute'), this.width)} />
```

and now the initial render looks good, but reactivity is still not being triggered.

**Comment by trusktr** [comment]
This is what the output for the attribute expression looks like:

```js
      Object(solid_js_dom__WEBPACK_IMPORTED_MODULE_0__["wrap"])(() => _el$4.setAttribute("stroke-width", (console.log('re-run strokeWidth attribute'), _this.width)));
```

**Comment by ryansolid** [comment]
No I mean I use getter/setters and proxies all the time. If `_this.width` is reactive it should be registering it. wrap is just an alias for `createEffect`. I feel we're missing something else. Something not visible in the code posted here.

**Comment by trusktr** [comment]
I'll keep investigating. It just isn't working. I'm 100% sure `_this.width` is reactive. Because I have the following, and it works great:

```js
connectedCallback() {
    createEffect(() => {
      console.log(this.width) // logs many times. But the JSX expression doesn't
    })
}
```

**Comment by trusktr** [comment]
No luck finding what the issue is yet, but I changed my JSX from

```jsx
<line stroke-width={(console.log('re-run strokeWidth attribute'), this.width)} />
```

to

```jsx
const line = <line stroke-width={this.width} />
createEffect(() => {
  line.setAttribute('stroke-width', '' + this.width)
})
```

and now it successfully updates the attribute and repeatedly logs to console.

**Comment by trusktr** [comment]
I upgraded to `babel-preset-solid` 0.12.0, but the issue persists. (Is that the version that adds the heuristic instead of requiring `()`?).

**Comment by ryansolid** [comment]
Yes that is correct. I have never seen anything like this before since the generated code looks right. Which suggests an issue with element behavior. It might be related to the SVG stuff we have been seeing. I'm going to make fixing SVG's my top priority.

**Comment by ryansolid** [comment]
I believe I've fixed the SVG issues with Babel Plugin JSX DOM Expressions v0.13.2. Unfortunately, my codesandboxes don't seem to want to update. But I'm hoping if you try again this will be resolved.

**Comment by trusktr** [comment]
Cool, I verified that the standalone `<line />` element works, instantiated as an `SVGLineElement`.

I'm still having issues with the reactivity though.

**Comment by trusktr** [comment]
Hmm, I think I may know what the problem is: I have two versions of `solid-js` in my `node_modules`:

```
❯ npm ls solid-js                                                                                                ✖ ✹ ✭
tracker@1.1.0 /Users/trusktr/src/tracker
├─┬ glas@0.0.0 -> /Users/trusktr/src/glas invalid
│ └── solid-js@0.10.11  extraneous
└── solid-js@0.10.11  extraneous
```

Is there's stuff in the `solid-js` package that expects it to essentially be a singleton, and wouldn't work with things like `createEffect` imported from another `solid-js`?

**Comment by trusktr** [comment]
The reason there are two of them, in my case, is because I'm using `npm link` to link a dependency of mine (for development) that also imports `solid-js`. If I had installed it normally, without linking, the `solid-js` dependency would be de-duped.

Maybe `solid-js` could use versioned global variables for storing things that it uses to track dependencies? Not sure how else to fix it (`npm link`ing is a common workflow).

**Comment by trusktr** [comment]
Yeah, I see stuff like

```js
let RootClock = createClock(),
  RunningClock = null as any, // currently running clock
  Listener = null as ComputationNode | null, // currently listening computation
  Owner = null as ComputationNode | null, // owner for new computations
  Pending = null as ComputationNode | null, // pending node
  LastNode = null as ComputationNode | null; // cached unused node, for re-use
```

at the top level of `signal.js`, so it'd make sense that cross-mixing the APIs probably wouldn't work as they'd be trying to read different variables.

**Comment by trusktr** [comment]
How could the following be made to work? (It's also something I want to think about for my own projects, as it'd be great to prevent other peeps from spending time figuring why things aren't working when they are using things exactly as documented.)

```js
import {createEffect as createEffect1} from 'solid-js1' // webpack alias to one location
import {createEffect as createEffect2} from 'solid-js2' // webpack alias to the other location

// ... make signals ...

createEffect1(() => {
  // ...
  createEffect2(() => {
    // ...
  })
})
```

**Comment by trusktr** [comment]
https://github.com/webpack/webpack/issues/985

**Comment by ryansolid** [comment]
I should have thought of suggesting this. I take it for granted a bit since I've had these sort of issues with numerous npm modules in the past. I imagine people using link like you do also hit this all the time. Reactive library tracking always based on some sort of singleton to track execution context so this can be an issue.

I'm glad you were able to to resolve this issue and thanks for the PR.
