### ISSUE TITLE
RFC: Automatic Reactive Binding Detection

### ISSUE THREAD

**Issue by ryansolid** [ryansolid/solid#91]
## Summary

Solid currently uses `{( )}` (parens syntax) to indicate that bindings should be wrapped in and a function and made reactive. Reactive computations have overhead so not creating unneeded ones can make large performance difference. This proposal suggests using a heuristic during compilation to determine reactivity instead implicitly.

**Looking for any feedback on the proposal. Please leave your thoughts in the comments below, or give a thumbs up and show your support**

## Motivation

While the parens syntax is very explicit and can lead to less serious or undetected bugs, it has several less than ideal consequences. It is unexpected as a syntax that serves as a blocker for newcomers. The syntax is very subtle so it's easy to forget. Finally shortcomings of Prettier prevent this syntax from working with it.

## Proposal

There are certain types of syntax that will never be reactive like function declarations, literal values.
```jsx
// these bindings never need to be wrapped
<div onClick={() => setState({clicked: true})} name={"mydiv"} />
```
Similarly since reactivity requires access only function calls or property accesses can be reactive. So simple variables will never need to be wrapped
```jsx
// also never needs to be wrapped
<div name={myName} maxlength={count * 2} />
```
So we can limit wrapping to only expressions that could be reactive like:
```jsx
// wrap because they could be reactive
<div name={props.name} title={getTitle()} />
```

Also for Component props that take Components like `fallback` or `children` we will wrap any expression with a tag to allow deferred evaluation.
```jsx
// these will be wrapped
<Show when={state.accepted} fallback={<Denied />}>
  <Accepted />
</Show>
```

What if you wish for these things to be static? Hoist the value access. Since normal variables aren't reactive just assign it to a variable. This is JSX so we have all the power of JavaScript at our side and do not need a special syntax.
```jsx
const name = props.name;
// not wrapped as simple variable
<div name={name} />
```

## Drawbacks
1. This approach looses explicitness. When looking at this solutions all the alternatives unfortunately were more verbose than the current parens syntax. Swapping the default also did not make sense as it was inconsistent in special cases like `onClick` or `ref`. The explicitness is really nice for those who are very particular with control but this simple heuristic actually handles all cases except explicitly static access well.

2. Spreads now need to all be dynamic. It means in a few optimized cases there will be more overhead on spreads than before. But to be fair spreads were always an all or nothing thing so more often than not all spreads would be dynamic anyway.

3. Conventions around statics can cause runaway computation loops if end users do Component inserts inside expressions instead of using Control Flow or normal JSX. The common pattern for static props will likely look like this:
```jsx
function MyComponent(props) {
  // statics that never change
  const { id, type } = props;
  return <div id={id}>{props.name} {type} {props.description}</div>
}
```
If someone wraps this Component carelessly the dereference will get captured by the parent context.
```jsx
<div>{
  state.showMyComponent &&
    <MyComponent id="1" type={state.type} name={state.name} description={state.description} />
}</div>
```
Ie.. if state.type ever changed then the whole parent expression including executing the Component would get rerun. This can be a problem if there is some expensive operation in the child.

## Adoption

This syntax is breaking. It won't break current apps in the sense that they will still be reactive. But more so somethings that were static before will now not be causing some performance implications. Migration path is removing all the extra parens (easy to do with Prettier) and hoist out any statics outside of the bindings.

## Acknowledgements

Special thanks to @bikeshedder and @trusktr  for working through the details to get things to this point. I admittedly was skeptical at first. And now I'm pretty happy with this.

**Comment by trusktr** [comment]
> If someone wraps this Component carelessly the dereference will get captured by the parent context.
> 
> ```js-jsx
> <div>{
>   state.showMyComponent &&
>     <MyComponent id="1" type={state.type} name={state.name} description={state.description} />
> }</div>
> ```
> 
> Ie.. if state.type ever changed then the whole parent expression including executing the Component would get rerun. This can be a problem if there is some expensive operation in the child.


Can you also edit that to show an example of the correct way to do that right after? I'm guessing it is the following?

```jsx
<div>
  <Show when={state.showMyComponent}>
    <MyComponent id="1" type={state.type} name={state.name} description={state.description} />
  </Show>
</div>
```

In my attempt, does `MyComponent` only get created once and receive new values of `state.type` while `state.showMyComponent` is true?

**Comment by trusktr** [comment]
How do you feel about having `once()` to force static expressions, f.e. `type={once(state.type)}`? That might still be easier than having to hoist code out into a variable declaration.

**Comment by ryansolid** [comment]
> Can you also edit that to show an example of the correct way to do that right after? I'm guessing it is the following?
>In my attempt, does MyComponent only get created once and receive new values of state.type while state.showMyComponent is true?

Yes you are correct that is how you do. In this case, since the Component itself treats type as static nothing will get updated when `state.type` changes. However, when `state.name` or `state.description` change those text bindings in the div will update.

> How do you feel about having once() to force static expressions, f.e. type={once(state.type)}? That might still be easier than having to hoist code out into a variable declaration.

What ultimately won me over on this approach was realizing that since simple variables don't need to be wrapped I could do hoisting to make things static. I like the explicitness of the current system, but what I like more is not having a compiler forced detected syntax that end-users have to apply `{( )}`. That was the big win from my perspective. Adding `once` is just adding that back again. This is very different than the heuristics used in this proposal which are based on code the end-user would already be writing.

While nothing stops us from potentially adding this sort of compiler detected syntax (only typescript users would need to import it and tree-shaking would remove the faux function), I think we should see if there is a real need before going there. I'd much rather not have special syntaxes like this if avoidable.

**Comment by ryansolid** [comment]
Live with v0.12.0. Still feel free to leave any feedback. The base cases work but I'm sure there will be some edge cases.

**Comment by bluenote10** [comment]
Sorry for the late comment, I didn't had time to follow the activity here. 

I actually prefer the old behavior. I would have simply documented the `{(...)}` behavior as _the number one rule_ of Solid. In my opinion it was very nice to have explicit control over what is dynamic and what is static. 

In my/our projects at work, we are actually using the possibility of accessing (potentially dynamic) state/props in a static way a lot (for components/elements that have "referesh on load" behavior). How do we actually achieve static behavior now?

> hoist out any statics outside of the bindings.

But using `let mystateStatic = state.mystate` still gives a `Wrapper<T>`, so it is still dynamic, isn't it? Don't we need explicit unwrap? :thinking: 

In any case what I don't like about the hoisting-to-get-static:
- It is necessary to pollute the outer scope now with variables that don't seem necessary, and the decision whether something is static/dynamic isn't a local edit anymore -- we need to edit both the JSX and the surrounding scope / jumping around in the code to edit the statics.
- Beginners might still be confused why Solid behaves differently when passing `state.mystate` directly vs hosting it in a variable. To them the hoisting has no semantic meaning, i.e., if the variable `mystate` is only used once in the JSX, they may refactor it to use `state.mystate` directly. One wouldn't expect that replacing the variable by its value affects behavior. To me this just shifts the things we need to learn about `{(...)}` to things we need to know about state/props hoisting.

I

**Comment by ryansolid** [comment]
Yeah to be fair as the guy writing benchmarks the old syntax was a lot more explicit. Although the syntax was the endless source of confusion and friction as well as awkward for tooling like code formatters. The motivation here is more along the lines of people not needing to think about this much at all anymore unless doing extreme optimization. I've been doing complementary work in the library to reduce the overhead of misappropriating static bindings. I actually don't actually expect people to be hoisting, we are just sort of cursed since we are in the know and I wanted to illustrate what it would take to do the equivalent.

We accomplish this because of 2 things:
1. Overhead of unnecessarily wrapping fields in Components is almost nothing. It's basically the cost of a closure (and an object getter). Ie.. the difference between `{value: state.value}` and `{value: () => state.value}`. Wasn't even sure initially I wanted to do the same syntax for Component bindings since they aren't actually creating bindings and just are a means for deferred access. From the point of execution and updates this is a very small cost.
2. The overhead of creating computations is much greater than the cost of updating multiple attributes or running simple diff on multiple attributes. By loosening the granularity a bit (the approach Surplus takes) we pay the same creation cost if there is 1 dynamic binding or 30. So the only real cost is if nothing is dynamic in the template scope and we create one extra computation node. This is an area that I'm continuing to do performance improvements and benchmarking. In fact this can be significantly faster than the older versions in situations where there are multiple bindings.

So instead of focusing on what is dynamic, the idea is that everything that could be dynamic will be and don't worry about the rest. To be clear when I say dynamic in a binding context I don't mean the data is dynamic, but that the binding is dynamic and needs to be explicitly wrapped (either in a function or a computation). If you pass `mystateStatic` or `mySignal` technically these can be used reactively lower down. They just won't be wrapped in another function to ensure their access is captured. All reactions are triggered from function call or property access.

So in basic it is more like this change is just removing this whole thing as a concept from a beginners point of view. To them things won't work differently. It is more that `mystateStatic` isn't wrapped as an optimization but it has no behaviour impact in terms of reactivity. That binding never would need to be wrapped. They will never notice a behaviour difference. If they are confused why something doesn't update when `mystate` updates, the explanation is simple. They accessed it outside of a binding(in your example). But that would have been true `{( )}` syntax or not.

As you highlighted the only case this really doesn't work with is where you explicitly don't want it to update when the value changes. Since if the value never changes there is minimal overhead. Admittedly by comparison I thought this was the minimal case. Is this the case what you are talking about? Where you are updating the data but intentionally updating? I actually didn't realize this implication of this syntax since other libraries of this nature generally always try to update when data does. I've always used other architectural ways to handle this. But I'm interested to see if there is a case and something I can do better here.

**Comment by ryansolid** [comment]
If it's any consolidation. I did add an option to indicate something is static in view. It's just a bit more verbose. You can add `/*@once*/` comment to the expression and the compiler will not evaluate it again and it will have the old static behavior. This probably landed too late but it is now part of the system to give control without hoisting.
