### ISSUE TITLE
Real life project

### ISSUE THREAD

**Issue by mrjjwright** [ryansolid/solid#93]
Been using on a work project, excellent ergonomics and as of the latest version, with it's prettier support etc, everything has been working great.  Thank-you Ryan!

**Comment by ryansolid** [comment]
Thanks for dropping by to let me know. I appreciate the feedback. I realized that my sharp view on performance and explicitness did get in the way of adoption. I'm glad it is working for you well now. I'm continuing to work on improving performance and protecting against dangerous patterns (my reason for explicitness in the first place). But I'm pretty happy with the API now. Look forward to a stable release in the next few months.

**Comment by mrjjwright** [comment]
Your effort on modernizing these styles is huge because you are correct that the API really matters.  Your thought leadership is huge.  And nobody will ever complain about performance.

**Comment by mrjjwright** [comment]
Still loving it!

**Comment by mrjjwright** [comment]
Also using the Lit expressions because my app builds templates dynamically in the browser.  Just an fyi.  My main app uses the JSX expressions.

**Comment by ryansolid** [comment]
Cool. Thanks for the bug report. I admittedly don't spend as much time in there since I can make a lot easier gains from JSX compilation.
