### ISSUE TITLE
For each on signals

### ISSUE THREAD

**Issue by mrjjwright** [ryansolid/solid#94]
I am starting Solid with signals because I naturally trust them more after over a year of usage, vs state.  I probably will move to state as I understand it more, because it looks awesome.  It looks like a `<For each={(signal())}>`, where the signal returns a list, still needs wrapping parens to dynamically render even in version `0.13.2` of `babel-plugin-jsx-dom-expressions`.   I can get you a reproducible code sample but it just showed up on a work project.

**Comment by ryansolid** [comment]
Hmm.. I would expect this to work from a compiler perspective. You are right I use state in most of my examples but the [Scoreboard](https://codesandbox.io/s/solid-scoreboard-sjpje) uses a signal from `createMemo` for the sorted list and my tests(https://github.com/ryansolid/solid/blob/master/test/dom/for.spec.jsx) are passing which are using a simple `createSignal` setup. So I wonder if something else is going on.

**Comment by mrjjwright** [comment]
Oh yes the Scoreboard does use a signal in a `For each` scenario without parens.  At this one `For each` call site of mine, the only one I have so far that uses a list,  I have to wrap mine in parens for it to dynamically render when the signal updates even though I don't in other places after upgrading.  I will spend a bit more time chasing this down to see if I can narrow it down.  Thanks!

**Comment by mrjjwright** [comment]
Oh just found my own bug after pasting this.  `model.selectedInsight() === insightType ? "true" : false`.  They don't let me use Typescript but definitely need some linting.  After fixing this it works (for some reason haha).
